#   Gurgaon Data Preprocessing(Flats)

## 1.1 Introduction and Setup
In this phase we will first import the raw and scraped data for the gurgaon flats and perform an analysis. To analyse we will first import required libraries and load our dataset in the pandas dataframe to know what we are working with.

In [45]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [46]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [47]:
df = pd.read_excel('C:\\capstone_project_dscience\\real_estate_project\\dataset\\flats.xlsx')

## 1.2 High Level Data Inspection
here we will see what are the dimensions of our dataset, how many attributes are there, attributes name and spot any missing values

In [48]:
df.head()

,property_name,link,society,price,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
0,2 BHK Flat in Krishna Colony,https://www.99acres.com/2-bhk-bedroom-apartmen...,maa bhagwati residency,45 Lac,"₹ 5,000/sq.ft.",Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ...",C68850746
1,2 BHK Flat in Ashok Vihar,https://www.99acres.com/2-bhk-bedroom-apartmen...,Apna Enclave,50 Lac,"₹ 7,692/sq.ft.",Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ...",H68850564
2,2 BHK Flat in Sohna,https://www.99acres.com/2-bhk-bedroom-apartmen...,Tulsiani Easy in Homes,40 Lac,"₹ 6,722/sq.ft.",Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ...",J68850120
3,2 BHK Flat in Sector 61 Gurgaon,https://www.99acres.com/2-bhk-bedroom-apartmen...,Smart World Orchard,1.47 Crore,"₹ 12,250/sq.ft.",Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,2023-12-01 00:00:00,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN,S68849476
4,2 BHK Flat in Sector 92 Gurgaon,https://www.99acres.com/2-bhk-bedroom-apartmen...,Parkwood Westend,70 Lac,"₹ 5,204/sq.ft.",Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ...",L47956793

In [49]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3028 entries, 0 to 3027
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    3028 non-null   str
 1   link             3028 non-null   str
 2   society          3027 non-null   str
 3   price            3008 non-null   str
 4   area             3015 non-null   str
 5   areaWithType     3009 non-null   str
 6   bedRoom          3009 non-null   str
 7   bathroom         3009 non-null   str
 8   balcony          3009 non-null   str
 9   additionalRoom   1695 non-null   str
 10  address          3003 non-null   str
 11  floorNum         3007 non-null   str
 12  facing           2128 non-null   str
 13  agePossession    3008 non-null   object
 14  nearbyLocations  2914 non-null   str
 15  description      3009 non-null   str
 16  furnishDetails   2204 non-null   str
 17  features         2595 non-null   str
 18  rating           2677 non-null   str
 19  property_id      3009 non-null   str
dtypes: object(1), str(19)
memory usage: 473.3+ KB

### 1.2.1 column dtype
        1) columns like price and area they are also of string type instead of numerical values
        2) columns like 'link' and 'property_id' are of no use

In [50]:
df.drop(columns=['link','property_id'], inplace=True)

In [51]:
df.shape

(3028, 18)

### 1.2.2 dataset shape
        1)number of rows in the dataset is 3028
        2) number of columns -> 20

## 1.3 cleaning and feature extraction
        property_name column
            1) i want to extract the sector name from the property_name column

In [52]:
df['property_name'].value_counts()

property_name
2 BHK Flat in Sohna                                126
3 BHK Flat in Sector 102 Gurgaon                    76
3 BHK Flat in Sector 65 Gurgaon                     57
3 BHK Flat in Sector 92 Gurgaon                     53
3 BHK Flat in Sector 69 Gurgaon                     51
2 BHK Flat in Sector 85 Gurgaon                     49
3 BHK Flat in Sector 83 Gurgaon                     47
3 BHK Flat in Sector 81 Gurgaon                     45
3 BHK Flat in Sector 79 Gurgaon                     44
3 BHK Flat in Sector 109 Gurgaon                    44
2 BHK Flat in Sector 107 Gurgaon                    39
3 BHK Flat in Sector 37D Gurgaon                    38
3 BHK Flat in Sector 90 Gurgaon                     38
2 BHK Flat in Sector 79 Gurgaon                     37
3 BHK Flat in Sector 85 Gurgaon                     36
3 BHK Flat in Sector 70 Gurgaon                     36
3 BHK Flat in Sector 37C Gurgaon                    35
3 BHK Flat in Sector 86 Gurgaon                     34
4 BHK Flat in Sector 92 Gurgaon                     33
2 BHK Flat in Sector 95 Gurgaon                     33
3 BHK Flat in Sector 104 Gurgaon                    32
4 BHK Flat in Sector 69 Gurgaon                     32
2 BHK Flat in Sector 102 Gurgaon                    30
3 BHK Flat in Sector 67 Gurgaon                     30
3 BHK Flat in Sector 108 Gurgaon                    30
3 BHK Flat in Sector-33 Sohna                       29
4 BHK Flat in Sector 90 Gurgaon                     29
3 BHK Flat in Sector 89 Gurgaon                     29
2 BHK Flat in Sector 89 Gurgaon                     26
3 BHK Flat in Sector 56 Gurgaon                     26
2 BHK Flat in Sector 81 Gurgaon                     25
4 BHK Flat in Sector 85 Gurgaon                     25
2 BHK Flat in Sector 86 Gurgaon                     24
2 BHK Flat in Sector 90 Gurgaon                     23
3 BHK Flat in Sector 113 Gurgaon                    23
3 BHK Flat in Sector 61 Gurgaon                     23
2 BHK Flat in Sector 68 Gurgaon                     22
3 BHK Flat in Sector 70A Gurgaon                    22
3 BHK Flat in Sector 84 Gurgaon                     22
2 BHK Flat in Sector 84 Gurgaon                     21
3 BHK Flat in Sohna                                 20
3 BHK Flat in Nirvana Country                       20
2 BHK Flat in Sector 99A Gurgaon                    19
3 BHK Flat in Sector 49 Gurgaon                     19
3 BHK Flat in Sector 107 Gurgaon                    19
3 BHK Flat in Sector 48 Gurgaon                     18
2 BHK Flat in Sector 37C Gurgaon                    18
3 BHK Flat in Sector 106 Gurgaon                    18
2 BHK Flat in Sector 65 Gurgaon                     18
3 BHK Flat in Sector 77 Gurgaon                     18
2 BHK Flat in Sector 108 Gurgaon                    18
2 BHK Flat in Sector-33 Sohna                       18
2 BHK Flat in Sector 61 Gurgaon                     17
4 BHK Flat in Sector 72 Gurgaon                     17
3 BHK Flat in Sector 66 Gurgaon                     17
2 BHK Flat in Sector 103 Gurgaon                    16
2 BHK Flat in Sector 37D Gurgaon                    16
3 BHK Flat in Sector 103 Gurgaon                    15
2 BHK Flat in Sector 104 Gurgaon                    15
2 BHK Flat in Sector 70A Gurgaon                    15
4 BHK Flat in Sector 81 Gurgaon                     15
4 BHK Flat in Sector 104 Gurgaon                    15
3 BHK Flat in Sector 88A Gurgaon                    14
1 BHK Flat in Sohna                                 14
3 BHK Flat in Sector 54 Gurgaon                     14
4 BHK Flat in Sector 65 Gurgaon                     14
2 BHK Flat in Sector 92 Gurgaon                     13
3 BHK Flat in Sector 99A Gurgaon                    13
3 BHK Flat in Sector 82 Gurgaon                     13
2 BHK Flat in Sector 74 Gurgaon                     13
2 BHK Flat in Sector 83 Gurgaon                     13
2 BHK Flat in Sector 82 Gurgaon                     13
4 BHK Flat in Sector 37D Gurgaon                    12
2 BHK Flat in Palam Vihar                           12
3 BHK Flat in Sector 95 Gurgaon                     12
3 BHK Flat in Sector 78 Gurgaon                     11
2 BHK Flat in Sector 95A Gurgaon                    11
3 BHK Flat in Sector 71 Gurgaon                     11
3 BHK Flat in Sector 1 Imt Manesar                  11
2 BHK Flat in Sector 113 Gurgaon                    10
1 BHK Flat in Sector 95 Gurgaon                     10
4 BHK Flat in Sector 110 Gurgaon                    10
3 BHK Flat in Palam Vihar                           10
4 BHK Flat in Sector 56 Gurgaon                     10
3 BHK Flat in Sector 22 Gurgaon                     10
2 BHK Flat in Sector 67A Gurgaon                    10
2 BHK Flat in Sector 88A Gurgaon                     9
2 BHK Flat in Sector 99 Gurgaon                      9
3 BHK Flat in Sector 53 Gurgaon                      9
2 BHK Flat in Sector 70 Gurgaon                      9
4 BHK Flat in Sector 111 Gurgaon                     9
3 BHK Flat in Sector 112 Gurgaon                     9
2 BHK Flat in Sector 69 Gurgaon                      9
3 BHK Flat in Sector 67A Gurgaon                     9
2 BHK Flat in Sector 93 Gurgaon                      8
2 BHK Flat in Sector 106 Gurgaon                     8
3 BHK Flat in Sector 82A Gurgaon                     8
2 BHK Flat in Sector 71 Gurgaon                      8
2 BHK Flat in Sector 77 Gurgaon                      8
3 BHK Flat in Sector 63A Gurgaon                     8
4 BHK Flat in Sector 113 Gurgaon                     8
4 BHK Flat in Sector 48 Gurgaon                      8
3 BHK Flat in Sector 72 Gurgaon                      8
4 BHK Flat in Sector 67 Gurgaon                      8
4 BHK Flat in Sector 106 Gurgaon                     8
1 BHK Flat in Sector 56 Gurgaon                      8
3 BHK Flat in Dwarka Expressway Gurgaon              7
4 BHK Flat in Sector 108 Gurgaon                     7
2 BHK Flat in Sector 3 Gurgaon                       7
4 BHK Flat in Sector 91 Gurgaon                      7
4 BHK Flat in Sector 103 Gurgaon                     7
4 BHK Flat in Gwal Pahari                            7
3 BHK Flat in Sector 1A IMT Manesar                  7
4 BHK Flat in Sector 112 Gurgaon                     7
4 BHK Flat in Sector 62 Gurgaon                      7
2 BHK Flat in Sector 78 Gurgaon                      7
4 BHK Flat in DLF Phase 5                            7
3 BHK Flat in Sector 111 Gurgaon                     7
4 BHK Flat in Sector 109 Gurgaon                     7
3 BHK Flat in Sector 63 Gurgaon                      7
3 BHK Flat in Sector 76 Gurgaon                      7
2 BHK Flat in Sector 63A Gurgaon                     7
2 BHK Flat in Sector 33 Gurgaon                      6
4 BHK Flat in Sector 82 Gurgaon                      6
2 BHK Flat in DLF Phase 4                            6
2 BHK Flat in Laxman Vihar                           6
2 BHK Flat in Sector 22 Gurgaon                      6
4 BHK Flat in Sector 82A Gurgaon                     6
3 BHK Flat in Sector 36 Sohna                        6
3 BHK Flat in DLF Phase 5                            6
4 BHK Flat in Sector 9A Gurgaon                      6
3 BHK Flat in Sector 59 Gurgaon                      6
3 BHK Flat in DLF Phase 4                            6
4 BHK Flat in Sector 84 Gurgaon                      6
4 BHK Flat in Sector 54 Gurgaon                      6
4 BHK Flat in Sector 70 Gurgaon                      6
4 BHK Flat in Sector 102 Gurgaon                     6
2 BHK Flat in Sector 66 Gurgaon                      6
3 BHK Flat in Sector 68 Gurgaon                      6
2 BHK Flat in Sector 36A Gurgaon                     6
4 BHK Flat in Sector 99 Gurgaon                      6
3 BHK Flat in Gwal Pahari                            5
2 BHK Flat in Sector 62 Gurgaon                      5
4 BHK Flat in Sector 86 Gurgaon                      5
3 BHK Flat in Sector 9A Gurgaon                      5
3 BHK Flat in Sector 74 Gurgaon                      5
3 BHK Flat in Sector 60 Gurgaon                      5
2 BHK Flat in Sector 112 Gurgaon                     5
1 BHK Flat in Palam Vihar                            5
4 BHK Flat in Sector 60 Gurgaon                      5
4 BHK Flat in Sector 66 Gurgaon                      5
2 BHK Flat in Sector 91 Gurgaon                      5
1 BHK Flat in Sector 71 Gurgaon                      5
4 BHK Flat in Sector 50 Gurgaon                      5
1 BHK Flat in Sector 36A Gurgaon                     5
3 BHK Flat in Sector 89 A Gurgaon                    5
4 BHK Flat in Sector 63 Gurgaon                      5
2 BHK Flat in New Palam Vihar                        4
3 BHK Flat in Sector 43 Gurgaon                      4
4 BHK Flat in Sector 52 Gurgaon                      4
3 BHK Flat in Sushant Lok Phase 1                    4
5 BHK Flat in Sector 110 Gurgaon                     4
3 BHK Flat in Sector 47 Gurgaon                      4
2 BHK Flat in Sector 60 Gurgaon                      4
4 BHK Flat in Sector 83 Gurgaon                      4
4 BHK Flat in Sector 49 Gurgaon                      4
4 BHK Flat in Sector 53 Gurgaon                      4
5 BHK Flat in Sector 49 Gurgaon                      4
3 BHK Flat in Sector 80 Gurgaon                      4
1 BHK Flat in Sector 104 Gurgaon                     4
3 BHK Flat in Adarsh Nagar                           4
2 BHK Flat in Sector 76 Gurgaon                      4
3 BHK Flat in Mehrauli Gurgaon Road                  4
2 BHK Flat in Sector 88B Gurgaon                     3
4 BHK Flat in Sector 43 Gurgaon                      3
2 BHK Flat in Sector 10A Gurgaon                     3
4 BHK Flat in Sector 1A IMT Manesar                  3
3 BHK Flat in Sector 30 Gurgaon                      3
1 BHK Flat in Sector 67 Gurgaon                      3
2 BHK Flat in Ashok Vihar Phase 2                    3
2 BHK Flat in Sector 111 Gurgaon                     3
5 BHK Flat in Sector 82A Gurgaon                     3
3 BHK Flat in Sector 62 Gurgaon                      3
1 BHK Flat in Sector 83 Gurgaon                      3
4 BHK Flat in DLF Phase 2                            3
3 BHK Flat in DLF Phase 3                            3
4 BHK Flat in Sector 77 Gurgaon                      3
3 BHK Flat in Sector 39 Gurgaon                      3
3 BHK Flat in Sector 1 Gurgaon                       3
3 BHK Flat in sector 58 Gurgaon                      3
4 BHK Flat in Sector 71 Gurgaon                      3
3 BHK Flat in Sector 52 Gurgaon                      3
3 BHK Flat in Sector 91 Gurgaon                      3
1 BHK Flat in Sector 103 Gurgaon                     3
3 BHK Flat in IMT Manesar                            3
4 BHK Flat in Sector 70A Gurgaon                     3
2 BHK Flat in sector 58 Gurgaon                      3
3 BHK Flat in Chakkarpur                             3
4 BHK Flat in Mehrauli Gurgaon Road                  3
1 BHK Flat in Sector 49 Gurgaon                      3
4 BHK Flat in Sector 95 Gurgaon                      3
2 BHK Flat in Krishna Colony                         2
2 BHK Flat in Ashok Vihar                            2
2 BHK Flat in Sector 36 Gurgaon                      2
2 BHK Flat in Ashok Vihar Phase 3 Extension          2
1 BHK Flat in Block A Surya Vihar                    2
1 BHK Flat in Sector 84 Gurgaon                      2
3 BHK Flat in Sector 33 Gurgaon                      2
4 BHK Flat in Sector 67A Gurgaon                     2
2 BHK Flat in Sohna Road                             2
3 BHK Flat in IFFCO Chowk                            2
3 BHK Flat in Malibu Town                            2
3 BHK Flat in Sector 99 Gurgaon                      2
4 BHK Flat in Sector 68 Gurgaon                      2
4 BHK Flat in Sector 1 Imt Manesar                   2
2 BHK Flat in Sector 47 Gurgaon                      2
2 BHK Flat in Sector-11 sohna                        2
1 BHK Flat in Sector 28 Gurgaon                      2
5 BHK Flat in Sector 14 Gurgaon                      2
4 BHK Flat in Sector 22 Gurgaon                      2
2 BHK Flat in Sector 30 Gurgaon                      2
4 BHK Flat in Sector 107 Gurgaon                     2
1 BHK Flat in Sector 2 Gurgaon                       2
3 BHK Flat in Manesar                                2
2 BHK Flat in Nirvana Country                        2
5 BHK Flat in Sector 113 Gurgaon                     2
3 BHK Flat in Sector 110 A Gurgaon                   2
3 BHK Flat in MG Road                                2
4 BHK Flat in Sector 59 Gurgaon                      2
1 BHK Flat in Sector 81 Gurgaon                      2
1 BHK Flat in Sector 106 Gurgaon                     2
4 BHK Flat in Sector-33 Sohna                        2
2 BHK Flat in Sector 23A Gurgaon                     2
1 BHK Flat in Sector 111 Gurgaon                     2
1 BHK Flat in Sector 52 Gurgaon                      2
2 BHK Flat in Sector 89 A Gurgaon                    2
2 BHK Flat in Sector 2 Gurgaon                       2
1 BHK Flat in Sector 51 Gurgaon                      2
4 BHK Flat in New Gurgaon                            2
2 BHK Flat in Sector 11 Gurgaon                      2
3 BHK Flat in Sector 32 Gurgaon                      2
2 BHK Flat in Gwal Pahari                            2
5 BHK Flat in Sector 48 Gurgaon                      2
3 BHK Flat in Sector 36A Gurgaon                     2
4 BHK Flat in Valley View Estate                     2
4 BHK Flat in Sushant Lok                            2
5 BHK Flat in Sector 52 Gurgaon                      2
2 BHK Flat in Samaspur                               2
3 BHK Flat in Ashok Vihar Phase 2                    2
1 BHK Flat in Surat Nagar 1                          2
1 BHK Flat in Sispal Vihar                           2
4 BHK Flat in Shankar Vihar                          2
3 BHK Flat in Sector-2 Sohna                         2
3 BHK Flat in Sector 93 Gurgaon                      2
4 BHK Flat in Sector 24 Gurgaon                      2
3 BHK Flat in Sector 12 Gurgaon                      2
6 BHK Flat in Sector 70 Gurgaon                      2
4 BHK Flat in Sector 55 Gurgaon                      2
2 BHK Flat in New Gurgaon                            2
2 BHK Flat in Dayanand Colony                        2
3 BHK Flat in Sector 105 Gurgaon                     2
4 BHK Flat in DLF Phase 4                            2
3 BHK Flat in Rajendra Park                          2
2 BHK Flat in Godrej Aria , sector 79 , Gurgaon      2
1 BHK Flat in Sector 62 Gurgaon                      1
5 BHK Flat in Sector 1 Gurgaon                       1
2 BHK Flat in Sector-7 Housing Board                 1
3 BHK Flat in Sector 57 Gurgaon                      1
5 BHK Flat in Sector 66 Gurgaon                      1
2 BHK Flat in Sector 15 Part 1                       1
1 BHK Flat in Sector 109 Gurgaon                     1
1 BHK Flat in Sector 78 Gurgaon                      1
3 BHK Flat in Sector 12A Gurgaon                     1
2 BHK Flat in Rajiv Colony                           1
3 BHK Flat in Sector 2 Gurgaon                       1
3 BHK Flat in Garauli Kalan                          1
3 BHK Flat in Bhawani Enclave                        1
2 BHK Flat in Sector 82A Gurgaon                     1
4 BHK Flat in Palam Vihar                            1
4 BHK Flat in near sector 1 market                   1
2 BHK Flat in Sector 7 Gurgaon                       1
3 BHK Flat in Sohna Road                             1
2 BHK Flat in Golf Course Road                       1
2 BHK Flat in Sector 4 Gurgaon                       1
2 BHK Flat in Chakkarpur                             1
4 BHK Flat in Sector 41 Gurgaon                      1
2 BHK Flat in Sector 12 Gurgaon                      1
3 BHK Flat in Sector 73 Gurgaon                      1
4 BHK Flat in Sector 78 Gurgaon                      1
3 BHK Flat in Sector 4 Gurgaon                       1
1 BHK Flat in Sector 63 Gurgaon                      1
property_name                                        1
4 BHK Flat in Sector 33 Gurgaon                      1
3 BHK Flat in Kanahi                                 1
4 BHK Flat in DLF Phase 3                            1
3 BHK Flat in Heritage City                          1
4 BHK Flat in Sector 1 Gurgaon                       1
4 BHK Flat in Sector 38 Gurgaon                      1
4 BHK Flat in Sector 15 Gurgaon                      1
3 BHK Flat in Ambience Island                        1
4 BHK Flat in Ambience Island                        1
5 BHK Flat in Sector 106 Gurgaon                     1
3 BHK Flat in Sector 45 Gurgaon                      1
4 BHK Flat in Sector 61 Gurgaon                      1
4 BHK Flat in Sector 47 Gurgaon                      1
5 BHK Flat in Sector 51 Gurgaon                      1
3 BHK Flat in Sector 50 Gurgaon                      1
4 BHK Flat in Suncity                                1
4 BHK Flat in Sector 110 A Gurgaon                   1
5 BHK Flat in Sector 39 Gurgaon                      1
1 BHK Flat in Sector 92 Gurgaon                      1
5 BHK Flat in Gwal Pahari                            1
3 BHK Flat in Sai Kunj                               1
5 BHK Flat in Sector 83 Gurgaon                      1
4 BHK Flat in Sector 99A Gurgaon                     1
4 BHK Flat in Sector 39 Gurgaon                      1
5 BHK Flat in Sector 62 Gurgaon                      1
2 BHK Flat in Sector 1 Imt Manesar                   1
4 BHK Flat in Sector 37C Gurgaon                     1
4 BHK Flat in sector 58 Gurgaon                      1
3 BHK Flat in Sector 55 Gurgaon                      1
3 BHK Flat in Sultanpur                              1
4 BHK Flat in Sushant Lok Phase 1                    1
3 BHK Flat in Suncity                                1
4 BHK Flat in MG Road                                1
2 BHK Flat in Sector 51 Gurgaon                      1
3 BHK Flat in Civil Lines                            1
3 BHK Flat in Sector 28 Gurgaon                      1
5 BHK Flat in Sector 57 Gurgaon                      1
3 BHK Flat in New Colony, Sector 7                   1
1 BHK Flat in Sector 31 Gurgaon                      1
3 BHK Flat in Sector 31 Gurgaon                      1
2 BHK Flat in Sector 67 Gurgaon                      1
4 BHK Flat in Sector 31 Gurgaon                      1
3 BHK Flat in Lajpat Nagar                           1
4 BHK Flat in Sector 51 Gurgaon                      1
3 BHK Flat in Sector 7 Gurgaon                       1
1 BHK Flat in Sector 63A Gurgaon                     1
2 BHK Flat in Sector 73 Gurgaon                      1
4 BHK Flat in Sector 79 Gurgaon                      1
6 BHK Flat in Sector 10A Gurgaon                     1
5 BHK Flat in DLF Phase 2                            1
5 BHK Flat in Surya Vihar                            1
2 BHK Flat in Near Pataudi Chowk                     1
4 BHK Flat in Cyber City                             1
3 BHK Flat in New Colony                             1
3 BHK Flat in Sector 51 Gurgaon                      1
2 BHK Flat in Subhash Nagar                          1
4 BHK Flat in Sector 93 Gurgaon                      1
3 BHK Flat in ats marigold                           1
3 BHK Flat in Sector 15 Gurgaon                      1
2 BHK Flat in Sector-2 Sohna                         1
4 BHK Flat in Sector 37A Gurgaon                     1
4 BHK Flat in Sector 45 Gurgaon                      1
3 BHK Flat in Sushant Lok Phase 3                    1
2 BHK Flat in Carterpuri Village                     1
1 BHK Flat in Sector 102 Gurgaon                     1
2 BHK Flat in Sector 31 Gurgaon                      1
3 BHK Flat in Shanti Nagar                           1
1 BHK Flat in Laxman Vihar Phase 2                   1
2 BHK Flat in Sector-5 Sohna                         1
2 BHK Flat in Gurgaon Faridabad Road                 1
1 BHK Flat in Sector 107 Gurgaon                     1

     here i extracted the sector detail from the property_name column

In [53]:
sectors = df['property_name'].str.split('in').str.get(1).str.split('Gurgaon').str.get(0).str.strip()

    created a new column for the sectors

In [54]:
df.insert(1, 'sector', sectors)

In [55]:
df.head()

,property_name,sector,society,price,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,Krishna Colony,maa bhagwati residency,45 Lac,"₹ 5,000/sq.ft.",Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,Ashok Vihar,Apna Enclave,50 Lac,"₹ 7,692/sq.ft.",Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,Sohna,Tulsiani Easy in Homes,40 Lac,"₹ 6,722/sq.ft.",Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,Sector 61,Smart World Orchard,1.47 Crore,"₹ 12,250/sq.ft.",Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,2023-12-01 00:00:00,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,Sector 92,Parkwood Westend,70 Lac,"₹ 5,204/sq.ft.",Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [56]:
df['sector'] = df['sector'].str.lower()

In [57]:
df['sector'].value_counts()

sector
sohna                            160
sector 102                       113
sector 85                        110
sector 92                        100
sector 69                         92
sector 90                         90
sector 65                         89
sector 81                         87
sector 79                         82
sector 83                         68
sector 104                        66
sector 37d                        66
sector 86                         63
sector 107                        61
sector 95                         58
sector 108                        55
sector 89                         55
sector 37c                        55
sector 70                         53
sector 109                        52
sector 84                         51
sector-33 sohna                   49
sector 56                         44
sector 113                        43
sector 67                         42
sector 61                         41
sector 103                        41
sector 70a                        40
sector 106                        37
sector 99a                        33
sector 82                         32
sector 68                         30
sector 49                         30
sector 77                         29
sector 66                         29
sector 48                         28
palam vihar                       28
sector 71                         27
sector 72                         25
sector 88a                        24
nirvana country                   22
sector 67a                        21
sector 111                        21
sector 112                        21
sector 78                         20
sector 54                         20
sector 82a                        19
sector 22                         18
sector 74                         18
sector 62                         17
sector 99                         17
sector 63a                        16
sector 91                         15
gwal pahari                       15
sector 110                        15
dlf phase 4                       14
sector 1 imt manesar              14
sector 60                         14
sector 53                         13
sector 63                         13
dlf phase 5                       13
sector 36a                        13
sector 76                         12
sector 93                         11
sector 95a                        11
sector 52                         11
sector 9a                         11
sector 1a imt manesar             10
sector 33                          9
sector 47                          8
sector 59                          8
sector 89 a                        8
dwarka expressway                  7
sector 3                           7
sector 43                          7
sector 58                          7
mehrauli                           7
laxman vihar                       6
sector 36 sohna                    6
sector 51                          6
sector 50                          6
sector 1                           5
sector 10a                         5
sector 30                          5
sushant lok phase 1                5
ashok vihar phase 2                5
sector 2                           5
chakkarpur                         5
sector 39                          5
sector 80                          5
adarsh nagar                       5
new palam vihar                    4
dlf phase 2                        4
dlf phase 3                        4
sector 31                          4
new                                4
valley view estate                 4
ashok vihar                        3
sector 36                          3
sector 88b                         3
sohna road                         3
sector 12                          3
sector 28                          3
sector 110 a                       3
manesar                            3
imt manesar                        3
mg road                            3
sector 55                          3
sector-2 sohna                     3
dayanand colony                    3
golf course ext road               3
krishna colony                     2
ashok vihar phase 3 extension      2
block a surya vihar                2
sector 57                          2
iffco chowk                        2
sector 7                           2
malibu town                        2
sector 4                           2
sector 73                          2
sector-11 sohna                    2
sector 14                          2
sector 15                          2
ambience island                    2
sector 45                          2
suncity                            2
sector 23a                         2
sector 11                          2
sector 32                          2
sushant lok phase 3                2
shanti nagar                       2
sushant lok                        2
sector 21                          2
samaspur                           2
surat nagar 1                      2
sispal vihar                       2
shankar vihar                      2
sector 24                          2
sector 105                         2
dharam colony                      2
rajendra park                      2
godrej aria , sector 79 ,          2
sector-7 hous                      1
sector 15 part 1                   1
sector 12a                         1
rajiv colony                       1
garauli kalan                      1
bhawani enclave                    1
near sector 1 market               1
golf course road                   1
sector 41                          1
kanahi                             1
heritage city                      1
sector 38                          1
sai kunj                           1
sultanpur                          1
civil l                            1
new colony, sector 7               1
lajpat nagar                       1
surya vihar                        1
near pataudi chowk                 1
cyber city                         1
new colony                         1
subhash nagar                      1
ats marigold                       1
sector 37a                         1
carterpuri village                 1
laxman vihar phase 2               1
sector-5 sohna                     1
                                   1
sector 5 chowk                     1
old delhi road, opp sector-14      1
sector 5                           1
nirvana country pocket h           1
patel nagar                        1
new palam vihar phase 2            1
sector-35 sohna                    1
bhondsi                            1
palam vihar extension              1
saroop garden rajendra park        1
sector 4 urban estate              1
bptp                               1
south city 1                       1
sector 9                           1
c block sushant lok phase 1        1
sector 40                          1
Name: count, dtype: int64

***society column** <br>
        here in society column we can see that the some digits as well as characters are also attached with the names

In [58]:
df['society'].value_counts()

society
SS The Leaf3.8 ★                                     73
Tulip Violet4.3 ★                                    40
Shapoorji Pallonji Joyville Gurugram4.0 ★            39
Signature Global Park4.0 ★                           36
Shree Vardhman Victoria3.8 ★                         35
Tulip Violet4.2 ★                                    33
Smart World Orchard                                  32
Smart World Gems                                     32
Emaar MGF Emerald Floors Premier3.8 ★                32
Paras Dews                                           31
DLF The Ultima4.0 ★                                  31
DLF Regal Gardens3.9 ★                               30
Shree Vardhman Flora3.8 ★                            29
M3M Woodshire4.0 ★                                   29
La Vida by Tata Housing                              28
Signature Global Solera3.7 ★                         28
Godrej Nature Plus                                   27
BPTP Terra3.8 ★                                      25
Emaar Gurgaon Greens4.1 ★                            25
DLF New Town Heights 13.9 ★                          24
Eldeco Accolade3.8 ★                                 24
Experion The Heartsong3.9 ★                          24
Vatika Gurgaon 213.7 ★                               24
Bestech Park View Residency3.9 ★                     23
ATS Triumph3.9 ★                                     22
M3M Heights                                          22
Tata Primanti4.1 ★                                   22
Emaar Palm Gardens4.1 ★                              22
ROF Ananda                                           21
Sare Crescent Parc3.5 ★                              21
Godrej 1014.0 ★                                      20
Experion Windchants3.8 ★                             20
Supertech Araville                                   19
Sare Homes                                           19
Antriksh Heights3.7 ★                                19
Sobha City                                           18
CHD Avenue 713.6 ★                                   18
Ambience Creacions                                   18
Indiabulls Centrum Park3.7 ★                         18
ATS Tourmaline3.9 ★                                  18
Mapsko Mount Ville4.1 ★                              18
M3M Golfestate4.4 ★                                  17
GLS Arawali Homes3.8 ★                               17
Pareena Coban Residences                             17
M3M Skywalk                                          17
Conscient Heritage Max4.3 ★                          17
Godrej Summit3.7 ★                                   17
HCBS Sports Ville3.6 ★                               16
Godrej Oasis3.9 ★                                    16
Umang Monsoon Breeze                                 16
M3M Merlin3.7 ★                                      16
Bestech Park View Grand Spa4.3 ★                     16
Ansal Heights 86                                     15
Emaar MGF The Palm Drive4.1 ★                        15
Corona Optus3.9 ★                                    15
DLF The Primus3.9 ★                                  14
Umang Winter Hills3.9 ★                              14
Ramsons Kshitij3.7 ★                                 14
MVN Athens3.7 ★                                      14
Indiabulls Enigma                                    14
Ireo Victory Valley4.1 ★                             14
The Close North4.0 ★                                 14
Orchid Petals4.1 ★                                   14
Ireo Skyon4.0 ★                                      14
Vatika The Seven Lamps3.8 ★                          14
Imperia The Esfera                                   14
Central Park Flower Valley                           13
Bestech Park View Ananda4.2 ★                        13
Puri Emerald Bay3.7 ★                                13
Ireo The Corridors                                   13
Breez Global Hill View                               11
M3M Soulitude                                        11
Godrej Aria3.8 ★                                     11
Raheja Vedaanta3.6 ★                                 11
Adani M2K Oyster Grande3.9 ★                         11
TARC Maceo3.8 ★                                      11
SBTL Caladium                                        11
Alpha Corp GurgaonOne 844.0 ★                        11
DLF The Skycourt4.2 ★                                11
ILD Greens4.1 ★                                      10
Godrej Air                                           10
Pivotal Devaan                                       10
Breez Global Heights4.2 ★                            10
Emaar MGF Palm Hills4.0 ★                            10
Pyramid Urban Homes 2                                10
Zara Aavaas                                          10
Ramprastha The Edge Towers3.5 ★                      10
DLF New Town Heights 24.0 ★                          10
ATS Kocoon                                           10
Puri Diplomatic Greens4.0 ★                          10
Capital Residences 360                               10
Signature Global Synera3.4 ★                         10
Pareena Mi Casa                                       9
Parsvnath Green Ville3.9 ★                            9
Bestech Park View Sanskruti4.2 ★                      9
AIPL The Peaceful Homes3.9 ★                          9
Vatika City4.1 ★                                      9
Microtek Greenburg3.8 ★                               9
Bestech Altura                                        8
M3M Skycity                                           8
GLS Avenue 51                                         8
Assotech Blith                                        8
M3M Capital                                           8
Emaar Digihomes                                       8
Orris Aster Court Premier                             8
The Lions CGHS                                        8
Tulip Ivory3.5 ★                                      8
Vatika Lifestyle Homes3.8 ★                           8
ss                                                    8
AVL 36 Gurgaon3.7 ★                                   8
Birla Navya                                           8
Emaar Imperial Gardens3.8 ★                           7
Mapsko Casa Bella3.8 ★                                7
Sare Crescent Parc Royal Greens Phase 1               7
Signature Global City                                 7
Ansal Housing Highland Park                           7
Trisara Our Homes 3                                   7
AIPL Zen Residences                                   7
Orris Carnation Residency3.7 ★                        7
Sare Green ParC Phase 3                               7
Ireo The Grand Arch4.0 ★                              7
Signature Andour Heights3.8 ★                         7
Signature Global Orchard Avenue3.6 ★                  7
Vipul Lavanya3.9 ★                                    7
Supertech Hues                                        6
Ashiana Mulberry                                      6
DLF Regency Park 13.6 ★                               6
Signature Global City 63A                             6
Signature The Roselia3.6 ★                            6
Greenopolis                                           6
Hero Homes                                            6
Suncity Vatsal Valley                                 6
Sidhartha NCR One Phase 14.2 ★                        6
Signature Global Park 4                               6
HSIIDC Sidco Aravali                                  6
Bestech Park View City4.1 ★                           6
Mapsko Royale Ville3.7 ★                              6
Kiran Residency                                       6
Bestech Park View Spa Next4.0 ★                       6
Parsvnath Exotica3.7 ★                                6
Pyramid Urban                                         6
M3M Sierra 68                                         6
Pioneer Araya3.8 ★                                    6
BPTP Astaire Gardens3.7 ★                             6
Shapoorji Pallonji Joyville Gurugram                  6
Apna Enclave                                          5
Signature Global City 81                              5
Godrej Habitat                                        5
Silverglades The Melia                                5
Pareena Laxmi Apartments3.6 ★                         5
Satya The Hermitage3.5 ★                              5
Central Park Flower Valley Aqua Front Towers          5
Green Court3.7 ★                                      5
Ashiana Anmol3.5 ★                                    5
Signature Global the Millennia                        5
Tulip Monsella                                        5
M3M The Marina4.0 ★                                   5
Central Park Resorts4.4 ★                             5
DLF Regency Park 24.0 ★                               5
Signature Global City 92                              5
Pioneer Park3.8 ★                                     5
Emaar MGF Emerald Estate3.8 ★                         5
Vatika City Homes3.9 ★                                5
DLF Park Place4.1 ★                                   5
Ireo Uptown4.1 ★                                      5
Signature Global Grand IVA3.9 ★                       5
Adani Brahma Samsara Vilasa                           5
Signature Global City 37D Ph 2                        5
ATS Marigold                                          5
Conscient Elevate                                     5
Krisumi Waterfall Residences                          5
Essel Towers                                          5
Vatika Sovereign Park                                 5
Ramprastha Skyz                                       4
Signature The Serenas                                 4
DLF New Town Heights3.7 ★                             4
Lotus Homz4.0 ★                                       4
Unitech Vistas                                        4
ILD Grand                                             4
Global Hill View                                      4
Railway Officers RPF Society                          4
Raheja Navodaya3.6 ★                                  4
DLF The Skycourt                                      4
SS The Coralwood3.4 ★                                 4
Emaar Palm Heights                                    4
Krrish Provence Estate                                4
Orris Aster Court                                     4
Godrej Icon                                           4
Unitech Fresco3.8 ★                                   4
Prime Habitat                                         4
Tata Gurgaon Gateway3.8 ★                             4
HSIIDC Sidco Shivalik Apartments3.8 ★                 4
Godrej Frontier3.7 ★                                  4
Ramprastha Primera                                    4
Sare Petioles                                         4
Corona Gracieux                                       4
Vatika Xpressions                                     3
Raheja Revanta                                        3
Adani Aangan Arcade                                   3
Sare Green Parc                                       3
Chintels Paradiso3.9 ★                                3
Maxworth City Residences                              3
Deepak Minda                                          3
Unitech The Residences3.7 ★                           3
Sidhartha NCR One                                     3
Raheja Sampada                                        3
Bestech Park View City 23.9 ★                         3
AFNHB Jalvayu Vihar3.7 ★                              3
Pyramid Elite                                         3
Brisk Lumbini Terrace Homes                           3
My Home                                               3
Essel Tower                                           3
Krrish Florence Estate                                3
Piedmont Taksila heights3.6 ★                         3
Tulip White3.5 ★                                      3
Sapphire Eighty Three                                 3
DLF The Grove                                         3
Sukhshanti Apartment                                  3
SS Almeria                                            3
DLF Carlton Estate4.0 ★                               3
DLF Belvedere Towers3.8 ★                             3
AIPL Club Residences                                  3
Unitech Heritage City                                 3
Paras Quartier                                        3
Ambience Lagoon3.9 ★                                  3
Unitech Uniworld Gardens3.8 ★                         3
Raheja Atharva3.6 ★                                   3
Tulip Purple                                          3
Vatika Independent Floors3.8 ★                        3
Shree Arihant Apartment                               3
Mahindra Aura4.2 ★                                    3
Shri Banke Bihari Society3.8 ★                        3
Puri Diplomatic Greens3.9 ★                           3
Sunischit Apartments                                  3
Dhoot Time Residency4.0 ★                             3
ATS Kocoon4.2 ★                                       3
Spaze Privy3.9 ★                                      3
Tulip Lemon3.9 ★                                      3
Conscient Habitat3.6 ★                                3
Suncity Platinum Towers                               3
Spaze Privy AT43.9 ★                                  3
Apex Our Homes                                        3
Guru Gram Haryana CGHS4.1 ★                           3
Siddhartha Apartment                                  3
Kendriya Vihar4.1 ★                                   3
Whiteland Blissville                                  3
Signature Global Solera 2                             3
Pivotal Riddhi Siddhi                                 3
Unitech Sunbreeze                                     3
DLF The Arbour                                        3
Sare Green Parc 2                                     3
DLF Express Greens3.9 ★                               3
Spaze Privvy The Address3.9 ★                         3
Shri Ram Apartments                                   3
Tulip Petals3.6 ★                                     3
Sidhartha NCR Greens4.3 ★                             3
Valley View Estate                                    3
The Roselia 2                                         3
Satya Element One                                     3
DLF Royalton Tower                                    3
Smriti Apartment                                      3
Jammu and Kashmir Bank Employees CGHS3.7 ★            3
Tulsiani Easy in Homes                                2
BPTP Freedom Park Life4.0 ★                           2
Puri The Aravallis                                    2
Ramprastha City                                       2
Ardee City3.8 ★                                       2
Supertech Hilltown                                    2
Raheja Vanya                                          2
Vatika INXT Floors                                    2
Palam Vihar Society                                   2
M3M Urbana                                            2
Ansal Heights3.2 ★                                    2
Suncity Heights3.7 ★                                  2
Ramprastha The Atrium3.4 ★                            2
Today Callidora                                       2
Park Royal Apartment                                  2
Mapsko Paradise3.9 ★                                  2
MRG World Ultimus                                     2
BPTP Pedestal                                         2
Unitech Uniworld Gardens 23.4 ★                       2
Maruti Vihar                                          2
Vasant Appartments                                    2
Landmark The Residency                                2
Mahindra Luminare4.0 ★                                2
The Close South3.9 ★                                  2
lagoon apartment                                      2
Elan The Presidential                                 2
Pioneer Urban Presidia                                2
M3M Latitude                                          2
Ansal API Celebrity Suites                            2
CGHS Airport Apartment                                2
Bestech Spa Signature                                 2
Green Campus CHS                                      2
DLF The Crest3.6 ★                                    2
DLF The Icon3.7 ★                                     2
Professors Enclave CGHS                               2
BPTP Mansions Park Prime                              2
Paras Irene3.7 ★                                      2
DLF The Belaire3.9 ★                                  2
Suncity Avenue 1023.9 ★                               2
BPTP Amstoria3.8 ★                                    2
Emaar MGF The Enclave                                 2
Vipul Belmonte3.9 ★                                   2
Bestech Park View Sanskruti4.1 ★                      2
M3M Ikonic                                            2
The Penthouses at the Hibiscus                        2
SS Hibiscus                                           2
Viridian The Plaza 106                                2
Tulip Leaf                                            2
Tulip Violet                                          2
Vatika Emilia Floors3.7 ★                             2
Emaar MGF Palm Studios                                2
Orchid Island4.2 ★                                    2
Signature Global The Millennia 3                      2
M3M Sky Lofts                                         2
ROF Aalayas3.8 ★                                      2
AWHO Shanti Vihar4.0 ★                                2
Ansal API Esencia3.7 ★                                2
Raheja Atlantis3.8 ★                                  2
Central Park 2 Bellevue                               2
Tulip Orange3.9 ★                                     2
Adani Aangan Galleria                                 2
HCBS Sports Ville                                     2
Housing Board Colony                                  2
Sahara Grace                                          2
Aqua Front Towers                                     2
Oriental Valley CHS                                   2
NBCC Heights3.9 ★                                     2
Supertech Hill Town                                   2
Suncity Avenue 76                                     2
Godrej Nature Plus Serenity                           2
Ashiana Anmol                                         2
Ganga Apartment                                       2
Suposhaa Smartworld Orchard                           2
Mittal Surya Vihar                                    2
Residency Grand                                       2
Samaspurkunj                                          2
om appartments                                        2
Lavanya Apartments                                    2
Apartment                                             2
Vipul World Floors                                    2
Milan CGHS 9                                          2
Element One Service                                   2
Breeze Global Heights                                 2
Shapoorji Pallonji Joyville                           2
Dlf City                                              2
Silverglades Hightown Residences                      2
Surendra Avenue 69                                    2
Ambience Caitriona                                    2
Bhagwati Sadan                                        2
Sidhivinayak Apartments                               2
Chanderlok Society                                    2
ss residency                                          2
Uphar lakshya homes                                   2
Godrej Aria , sector 79 , Gurgaon                     2
maa bhagwati residency                                1

In [59]:
df['society'] = df['society'].str.lower()


    now lets remove these digits and characters from the names

In [60]:
df['society'] = df['society'].str.replace(r'[\d\★]', '', regex=True)

In [61]:
df['society'].value_counts()

society
ss the leaf.                                      73
tulip violet.                                     73
shapoorji pallonji joyville gurugram.             39
signature global park.                            36
shree vardhman victoria.                          35
dlf new town heights .                            34
smart world orchard                               32
smart world gems                                  32
emaar mgf emerald floors premier.                 32
paras dews                                        31
dlf the ultima.                                   31
dlf regal gardens.                                30
shree vardhman flora.                             29
mm woodshire.                                     29
la vida by tata housing                           28
signature global solera.                          28
godrej nature plus                                27
bptp terra.                                       25
emaar gurgaon greens.                             25
eldeco accolade.                                  24
experion the heartsong.                           24
vatika gurgaon .                                  24
bestech park view residency.                      23
ats triumph.                                      22
mm heights                                        22
tata primanti.                                    22
emaar palm gardens.                               22
rof ananda                                        21
sare crescent parc.                               21
godrej .                                          20
experion windchants.                              20
supertech araville                                19
sare homes                                        19
antriksh heights.                                 19
sobha city                                        18
chd avenue .                                      18
ambience creacions                                18
indiabulls centrum park.                          18
ats tourmaline.                                   18
mm skywalk                                        18
mapsko mount ville.                               18
mm golfestate.                                    17
gls arawali homes.                                17
pareena coban residences                          17
conscient heritage max.                           17
godrej summit.                                    17
hcbs sports ville.                                16
godrej oasis.                                     16
umang monsoon breeze                              16
mm merlin.                                        16
bestech park view grand spa.                      16
ansal heights                                     15
emaar mgf the palm drive.                         15
corona optus.                                     15
dlf the primus.                                   14
umang winter hills.                               14
ramsons kshitij.                                  14
mvn athens.                                       14
indiabulls enigma                                 14
ireo victory valley.                              14
the close north.                                  14
orchid petals.                                    14
ireo skyon.                                       14
vatika the seven lamps.                           14
imperia the esfera                                14
central park flower valley                        13
bestech park view ananda.                         13
puri emerald bay.                                 13
puri diplomatic greens.                           13
ireo the corridors                                13
breez global hill view                            11
dlf regency park .                                11
mm soulitude                                      11
godrej aria.                                      11
raheja vedaanta.                                  11
adani mk oyster grande.                           11
tarc maceo.                                       11
sbtl caladium                                     11
alpha corp gurgaonone .                           11
bestech park view sanskruti.                      11
dlf the skycourt.                                 11
signature global city                             10
ild greens.                                       10
godrej air                                        10
pivotal devaan                                    10
breez global heights.                             10
emaar mgf palm hills.                             10
pyramid urban homes                               10
zara aavaas                                       10
ramprastha the edge towers.                       10
ats kocoon                                        10
capital residences                                10
signature global synera.                          10
pareena mi casa                                    9
parsvnath green ville.                             9
aipl the peaceful homes.                           9
vatika city.                                       9
microtek greenburg.                                9
bestech altura                                     8
mm skycity                                         8
gls avenue                                         8
assotech blith                                     8
mm capital                                         8
emaar digihomes                                    8
orris aster court premier                          8
the lions cghs                                     8
tulip ivory.                                       8
vatika lifestyle homes.                            8
ss                                                 8
avl  gurgaon.                                      8
birla navya                                        8
emaar imperial gardens.                            7
mapsko casa bella.                                 7
sare crescent parc royal greens phase              7
signature global city                              7
ansal housing highland park                        7
trisara our homes                                  7
aipl zen residences                                7
sidhartha ncr one phase .                          7
orris carnation residency.                         7
sare green parc phase                              7
ireo the grand arch.                               7
signature andour heights.                          7
signature global orchard avenue.                   7
vipul lavanya.                                     7
supertech hues                                     6
ashiana mulberry                                   6
signature global city a                            6
signature the roselia.                             6
greenopolis                                        6
hero homes                                         6
suncity vatsal valley                              6
signature global park                              6
hsiidc sidco aravali                               6
bestech park view city.                            6
mapsko royale ville.                               6
kiran residency                                    6
bestech park view spa next.                        6
parsvnath exotica.                                 6
pyramid urban                                      6
mm sierra                                          6
pioneer araya.                                     6
bptp astaire gardens.                              6
shapoorji pallonji joyville gurugram               6
apna enclave                                       5
godrej habitat                                     5
silverglades the melia                             5
pareena laxmi apartments.                          5
satya the hermitage.                               5
central park flower valley aqua front towers       5
green court.                                       5
ashiana anmol.                                     5
signature global the millennia                     5
tulip monsella                                     5
mm the marina.                                     5
central park resorts.                              5
pioneer park.                                      5
emaar mgf emerald estate.                          5
vatika city homes.                                 5
dlf park place.                                    5
ireo uptown.                                       5
signature global grand iva.                        5
adani brahma samsara vilasa                        5
signature global city d ph                         5
ats marigold                                       5
conscient elevate                                  5
krisumi waterfall residences                       5
essel towers                                       5
vatika sovereign park                              5
ramprastha skyz                                    4
signature the serenas                              4
essel tower                                        4
dlf new town heights.                              4
lotus homz.                                        4
unitech vistas                                     4
ild grand                                          4
global hill view                                   4
railway officers rpf society                       4
raheja navodaya.                                   4
dlf the skycourt                                   4
ss the coralwood.                                  4
emaar palm heights                                 4
krrish provence estate                             4
orris aster court                                  4
godrej icon                                        4
unitech fresco.                                    4
prime habitat                                      4
tata gurgaon gateway.                              4
hsiidc sidco shivalik apartments.                  4
godrej frontier.                                   4
ramprastha primera                                 4
dlf the arbour                                     4
sare petioles                                      4
corona gracieux                                    4
vatika xpressions                                  3
raheja revanta                                     3
adani aangan arcade                                3
sare green parc                                    3
chintels paradiso.                                 3
maxworth city residences                           3
deepak minda                                       3
unitech the residences.                            3
sidhartha ncr one                                  3
raheja sampada                                     3
bestech park view city .                           3
afnhb jalvayu vihar.                               3
pyramid elite                                      3
brisk lumbini terrace homes                        3
my home                                            3
bhagwati sadan                                     3
krrish florence estate                             3
piedmont taksila heights.                          3
tulip white.                                       3
sapphire eighty three                              3
dlf the grove                                      3
sukhshanti apartment                               3
ss almeria                                         3
dlf carlton estate.                                3
dlf belvedere towers.                              3
aipl club residences                               3
unitech heritage city                              3
paras quartier                                     3
ambience lagoon.                                   3
unitech uniworld gardens.                          3
raheja atharva.                                    3
tulip purple                                       3
vatika independent floors.                         3
shree arihant apartment                            3
mahindra aura.                                     3
shri banke bihari society.                         3
sunischit apartments                               3
dhoot time residency.                              3
ats kocoon.                                        3
spaze privy.                                       3
tulip lemon.                                       3
conscient habitat.                                 3
suncity platinum towers                            3
spaze privy at.                                    3
apex our homes                                     3
guru gram haryana cghs.                            3
siddhartha apartment                               3
kendriya vihar.                                    3
whiteland blissville                               3
signature global solera                            3
pivotal riddhi siddhi                              3
unitech sunbreeze                                  3
sare green parc                                    3
dlf express greens.                                3
spaze privvy the address.                          3
shri ram apartments                                3
tulip petals.                                      3
sidhartha ncr greens.                              3
valley view estate                                 3
the roselia                                        3
satya element one                                  3
ss residency                                       3
dlf royalton tower                                 3
smriti apartment                                   3
jammu and kashmir bank employees cghs.             3
tulsiani easy in homes                             2
shree shyam residency                              2
bptp freedom park life.                            2
puri the aravallis                                 2
ramprastha city                                    2
ardee city.                                        2
supertech hilltown                                 2
raheja vanya                                       2
vatika inxt floors                                 2
palam vihar society                                2
mm urbana                                          2
ansal heights.                                     2
suncity heights.                                   2
ramprastha the atrium.                             2
today callidora                                    2
park royal apartment                               2
mapsko paradise.                                   2
mrg world ultimus                                  2
bptp pedestal                                      2
unitech uniworld gardens .                         2
maruti vihar                                       2
vasant appartments                                 2
landmark the residency                             2
mahindra luminare.                                 2
the close south.                                   2
lagoon apartment                                   2
elan the presidential                              2
pioneer urban presidia                             2
mm latitude                                        2
ansal api celebrity suites                         2
cghs airport apartment                             2
bestech spa signature                              2
green campus chs                                   2
dlf the crest.                                     2
dlf the icon.                                      2
professors enclave cghs                            2
bptp mansions park prime                           2
paras irene.                                       2
dlf the belaire.                                   2
suncity avenue .                                   2
bptp amstoria.                                     2
emaar mgf the enclave                              2
vipul belmonte.                                    2
mm ikonic                                          2
the penthouses at the hibiscus                     2
ss hibiscus                                        2
viridian the plaza                                 2
tulip leaf                                         2
tulip violet                                       2
vatika emilia floors.                              2
emaar mgf palm studios                             2
orchid island.                                     2
signature global the millennia                     2
mm sky lofts                                       2
rof aalayas.                                       2
awho shanti vihar.                                 2
ansal api esencia.                                 2
shyam apartment                                    2
raheja atlantis.                                   2
central park  bellevue                             2
tulip orange.                                      2
adani aangan galleria                              2
hcbs sports ville                                  2
housing board colony                               2
sahara grace                                       2
aqua front towers                                  2
oriental valley chs                                2
nbcc heights.                                      2
supertech hill town                                2
suncity avenue                                     2
godrej nature plus serenity                        2
ashiana anmol                                      2
ganga apartment                                    2
suposhaa smartworld orchard                        2
mittal surya vihar                                 2
residency grand                                    2
samaspurkunj                                       2
om appartments                                     2
lavanya apartments                                 2
apartment                                          2
vipul world floors                                 2
milan cghs                                         2
element one service                                2
breeze global heights                              2
shapoorji pallonji joyville                        2
dlf city                                           2
silverglades hightown residences                   2
surendra avenue                                    2
ambience caitriona                                 2
sidhivinayak apartments                            2
chanderlok society                                 2
uphar lakshya homes                                2
godrej aria , sector  , gurgaon                    2
maa bhagwati residency                             1
parkwood westend                                   1
signature global infinity mall                     1
the cocoon                                         1
godrej                                             1
senate court                                       1
signature global orchard avenue                    1
the new people apartments                          1
the serenas                                        1
central park resort belgravia residences           1
apex builders                                      1
ompee k s residency                                1
bhawna cghs                                        1
ansal sushant lok ci                               1
godrej meridien                                    1
pooja apartment                                    1
gokuldham society, bahadurgarh                     1
s aradhya homes                                    1
emaar mgf palm terraces                            1
anamika enclave                                    1
huda ashok vihar phase .                           1
emaar palm premier                                 1
conscient one                                      1
not applicable                                     1
smartworld dxp                                     1

**price**<br>

In [62]:
df['price'].value_counts()

price
1.25 Crore          79
1.1 Crore           61
1.4 Crore           60
1.2 Crore           59
1.5 Crore           59
90 Lac              58
1.3 Crore           57
95 Lac              53
2 Crore             51
1.75 Crore          47
1 Crore             46
1.6 Crore           43
1.35 Crore          41
1.55 Crore          40
1.9 Crore           40
75 Lac              38
1.65 Crore          38
1.8 Crore           37
1.7 Crore           37
80 Lac              36
2.2 Crore           34
50 Lac              33
1.15 Crore          33
85 Lac              31
1.45 Crore          31
1.05 Crore          30
40 Lac              29
2.5 Crore           29
60 Lac              29
45 Lac              26
2.1 Crore           26
65 Lac              25
1.85 Crore          23
2.35 Crore          23
35 Lac              23
3 Crore             22
70 Lac              21
2.25 Crore          20
55 Lac              20
3.5 Crore           19
2.4 Crore           18
2.3 Crore           18
30 Lac              17
2.65 Crore          16
1.38 Crore          15
2.6 Crore           15
2.15 Crore          14
3.4 Crore           14
2.45 Crore          14
3.25 Crore          13
82 Lac              13
78 Lac              13
2.7 Crore           13
38 Lac              13
1.32 Crore          13
92 Lac              13
42 Lac              12
2.8 Crore           12
1.95 Crore          12
1.42 Crore          12
5 Crore             12
Price on Request    11
25 Lac              11
32 Lac              11
88 Lac              11
1.08 Crore          11
28 Lac              10
26 Lac              10
87 Lac              10
1.28 Crore          10
2.55 Crore          10
1.78 Crore          10
1.12 Crore          10
2.85 Crore           9
99 Lac               9
22 Lac               9
36 Lac               9
2.05 Crore           9
4 Crore              9
3.45 Crore           9
1.68 Crore           9
1.72 Crore           9
86 Lac               8
3.2 Crore            8
56 Lac               8
2.75 Crore           8
27 Lac               8
4.25 Crore           8
1.18 Crore           8
1.54 Crore           8
6.5 Crore            8
6 Crore              8
1.76 Crore           8
98 Lac               8
1.26 Crore           8
48 Lac               8
20 Lac               8
1.99 Crore           7
79 Lac               7
46 Lac               7
1.29 Crore           7
2.9 Crore            7
39 Lac               7
72 Lac               7
97 Lac               7
3.7 Crore            7
1.27 Crore           7
1.36 Crore           7
3.3 Crore            7
1.19 Crore           7
1.02 Crore           7
96 Lac               6
1.01 Crore           6
43 Lac               6
3.35 Crore           6
54 Lac               6
4.1 Crore            6
71.5 Lac             6
1.49 Crore           6
3.9 Crore            6
1.98 Crore           6
3.65 Crore           6
5.5 Crore            6
1.07 Crore           6
1.51 Crore           6
2.95 Crore           6
3.05 Crore           6
1.16 Crore           6
21 Lac               6
1.59 Crore           6
1.14 Crore           6
1.39 Crore           6
1.34 Crore           6
1.13 Crore           6
37 Lac               6
1.47 Crore           5
29 Lac               5
1.83 Crore           5
93 Lac               5
4.5 Crore            5
64 Lac               5
24 Lac               5
1.79 Crore           5
2.29 Crore           5
66 Lac               5
1.93 Crore           5
2.12 Crore           5
3.75 Crore           5
6.75 Crore           5
1.33 Crore           5
49 Lac               5
2.78 Crore           5
1.24 Crore           5
1.17 Crore           5
2.22 Crore           5
1.82 Crore           5
1.43 Crore           5
1.91 Crore           5
1.69 Crore           5
1.44 Crore           5
1.92 Crore           5
68 Lac               5
1.62 Crore           5
3.95 Crore           4
6.15 Crore           4
74 Lac               4
28.5 Lac             4
1.71 Crore           4
1.48 Crore           4
5.6 Crore            4
5.9 Crore            4
1.64 Crore           4
3.6 Crore            4
1.77 Crore           4
1.52 Crore           4
62 Lac               4
1.73 Crore           4
5.25 Crore           4
1.37 Crore           4
1.31 Crore           4
1.58 Crore           4
2.09 Crore           4
41.5 Lac             4
1.22 Crore           4
4.3 Crore            4
4.85 Crore           4
7 Crore              4
3.1 Crore            4
1.66 Crore           4
31 Lac               4
89 Lac               4
73 Lac               4
36.5 Lac             4
33 Lac               4
1.23 Crore           4
67 Lac               4
58 Lac               4
4.75 Crore           3
83 Lac               3
34 Lac               3
3.85 Crore           3
2.33 Crore           3
2.79 Crore           3
1.41 Crore           3
91 Lac               3
3.49 Crore           3
1.67 Crore           3
4.8 Crore            3
2.51 Crore           3
2.01 Crore           3
2.08 Crore           3
69 Lac               3
1.09 Crore           3
2.28 Crore           3
3.8 Crore            3
2.03 Crore           3
1.04 Crore           3
2.24 Crore           3
52 Lac               3
3.15 Crore           3
1.21 Crore           3
2.36 Crore           3
1.57 Crore           3
64.5 Lac             3
1.88 Crore           3
84 Lac               3
51 Lac               3
5.8 Crore            3
1.63 Crore           3
72.5 Lac             3
4.2 Crore            3
94 Lac               3
47 Lac               3
41 Lac               2
31.5 Lac             2
2.91 Crore           2
59 Lac               2
3.29 Crore           2
71 Lac               2
87.5 Lac             2
52.56 Lac            2
5.7 Crore            2
1.56 Crore           2
2.26 Crore           2
2.99 Crore           2
2.87 Crore           2
2.57 Crore           2
5.2 Crore            2
4.6 Crore            2
3.21 Crore           2
3.32 Crore           2
1.87 Crore           2
3.55 Crore           2
98.5 Lac             2
56.2 Lac             2
88.5 Lac             2
4.7 Crore            2
4.45 Crore           2
27.75 Lac            2
2.04 Crore           2
4.55 Crore           2
7.5 Crore            2
11 Crore             2
27.1 Lac             2
2.58 Crore           2
2.14 Crore           2
53 Lac               2
77.5 Lac             2
6.2 Crore            2
2.23 Crore           2
53.5 Lac             2
4.49 Crore           2
2.52 Crore           2
2.13 Crore           2
2.17 Crore           2
8.5 Crore            2
8 Crore              2
1.46 Crore           2
25.5 Lac             2
4.26 Crore           2
2.41 Crore           2
2.02 Crore           2
14 Crore             2
6.25 Crore           1
29.99 Lac            1
23 Lac               1
31.75 Lac            1
3.87 Crore           1
29.5 Lac             1
3.67 Crore           1
8.25 Crore           1
price                1
2.37 Crore           1
4.67 Crore           1
3.39 Crore           1
3.63 Crore           1
2.34 Crore           1
3.79 Crore           1
5.49 Crore           1
6.3 Crore            1
11.25 Crore          1
7.15 Crore           1
2.82 Crore           1
54.99 Lac            1
4.95 Crore           1
5.31 Crore           1
3.19 Crore           1
4.4 Crore            1
4.63 Crore           1
2.98 Crore           1
66.99 Lac            1
4.78 Crore           1
6.16 Crore           1
5.3 Crore            1
2.72 Crore           1
2.21 Crore           1
89.5 Lac             1
2.48 Crore           1
99.5 Lac             1
3.83 Crore           1
95.75 Lac            1
3.46 Crore           1
5.4 Crore            1
55.6 Lac             1
98.1 Lac             1
2.63 Crore           1
55.5 Lac             1
1.11 Crore           1
6.44 Crore           1
7.56 Crore           1
4.79 Crore           1
2.97 Crore           1
94.25 Lac            1
80.5 Lac             1
93.75 Lac            1
85.5 Lac             1
68.5 Lac             1
79.9 Lac             1
71.2 Lac             1
27.5 Lac             1
23.5 Lac             1
35.5 Lac             1
4.94 Crore           1
10.75 Crore          1
9.14 Crore           1
8.35 Crore           1
81 Lac               1
26.1 Lac             1
1.06 Crore           1
2.11 Crore           1
6.1 Crore            1
5.75 Crore           1
10 Crore             1
24.5 Lac             1
17.5 Lac             1
20.5 Lac             1
47.5 Lac             1
2.77 Crore           1
42.5 Lac             1
2.61 Crore           1
65.5 Lac             1
53.2 Lac             1
90.5 Lac             1
52.5 Lac             1
2.62 Crore           1
4.86 Crore           1
5.15 Crore           1
9.3 Crore            1
1.74 Crore           1
4.21 Crore           1
4.16 Crore           1
4.52 Crore           1
1.84 Crore           1
8.44 Crore           1
13.2 Crore           1
2.92 Crore           1
2.38 Crore           1
97.5 Lac             1
2.64 Crore           1
2.49 Crore           1
63.4 Lac             1
2.06 Crore           1
2.07 Crore           1
44 Lac               1
2.32 Crore           1
1.86 Crore           1
85.75 Lac            1
87.99 Lac            1
86.99 Lac            1
9.95 Crore           1
9.2 Crore            1
49.5 Lac             1
16 Lac               1
2.86 Crore           1
86.92 Lac            1
94.99 Lac            1
88.4 Lac             1
3.72 Crore           1
57 Lac               1
95.5 Lac             1
96.07 Lac            1
19 Lac               1
70.85 Lac            1
7.52 Crore           1
40.3 Lac             1
32.5 Lac             1
2.96 Crore           1
1.53 Crore           1
82.5 Lac             1
61 Lac               1
15 Crore             1
7.8 Crore            1
1.97 Crore           1
39.5 Lac             1
4.02 Crore           1
3.98 Crore           1
54.8 Lac             1
2.69 Crore           1
2.54 Crore           1
37.5 Lac             1
97.04 Lac            1
3.23 Crore           1
7.9 Crore            1
6.02 Crore           1
29.8 Lac             1
94.5 Lac             1
2.44 Crore           1
9 Crore              1
3.99 Crore           1
64.45 Lac            1
37.1 Lac             1
7.4 Crore            1
3.78 Crore           1
98.88 Lac            1
68.85 Lac            1
26.9 Lac             1
26.5 Lac             1
73.53 Lac            1
89.77 Lac            1
62.5 Lac             1
Name: count, dtype: int64

In [63]:
df['price'] = df['price'].str.lower()

    the price column is string dtype here. so i converted every value(except price on value and NAN) to crore and make them float type

In [64]:
def price_to_number(price):
    if pd.isna(price):
        return np.nan
    if 'lac' in price:
        return float(price.replace('lac','').strip())/100
    elif 'crore' in price:
        return float(price.replace('crore','').strip())
    else: return price
    

df['price'] = df['price'].apply(price_to_number)

In [65]:
df.head()

,property_name,sector,society,price,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,krishna colony,maa bhagwati residency,0.45,"₹ 5,000/sq.ft.",Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,ashok vihar,apna enclave,0.5,"₹ 7,692/sq.ft.",Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,sohna,tulsiani easy in homes,0.4,"₹ 6,722/sq.ft.",Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,sector 61,smart world orchard,1.47,"₹ 12,250/sq.ft.",Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,2023-12-01 00:00:00,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,sector 92,parkwood westend,0.7,"₹ 5,204/sq.ft.",Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

    remove the 286 index row beacause it is of no use

In [66]:
df.iloc[285:290]

,property_name,sector,society,price,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
285,3 BHK Flat in Sector 85 Gurgaon,sector 85,ss the leaf.,1.93,"₹ 8,075/sq.ft.",Super Built up area 2408(223.71 sq.m.)Built Up...,3 Bedrooms,4 Bathrooms,3 Balconies,Servant Room,"000000, Sector 85 Gurgaon, Gurgaon, Haryana",7th of 26 Floors,North-East,1 to 5 Year Old,"['Sapphire 83 Mall', 'Dwarka Expressway', 'Cen...",Ss the leaf is one of gurgaon's most sought af...,"['3 Wardrobe', '4 Fan', '10 Light', 'No AC', '...","['Centrally Air Conditioned', 'Water purifier'...","['Connectivity4.5 out of 5', 'Management4 out ..."
286,property_name,NaN,society,price,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
287,4 BHK Flat in Sector 113 Gurgaon,sector 113,smart world one dxp,3.45,"₹ 13,269/sq.ft.",Super Built up area 2600(241.55 sq.m.),4 Bedrooms,4 Bathrooms,3 Balconies,"Study Room,Servant Room","A121212, Sector 113 Gurgaon , Gurgaon, Haryana",11st of 30 Floors,South-East,2025-12-01 00:00:00,"['Palam Vihar Vyapar kendra', 'Ram Mandir', 'D...",Smart world soon bringing futuristic homes of ...,"['1 Geyser', '1 Microwave', '6 Light', '6 AC',...","['Centrally Air Conditioned', 'Water purifier'...",NaN
288,3 BHK Flat in Sector 56 Gurgaon,sector 56,sukhshanti apartment,1.7,"₹ 7,727/sq.ft.",Built Up area: 2200 (204.39 sq.m.)Carpet area:...,3 Bedrooms,3 Bathrooms,3 Balconies,Study Room,"402, Sector 56 Gurgaon, Gurgaon, Haryana",4th of 8 Floors,South,5 to 10 Year Old,"['Sector metro station', 'Sector metro station...",Opposite dlf metro station\nBest for office go...,NaN,"['Feng Shui / Vaastu Compliant', 'Security / F...","['Connectivity5 out of 5', 'Lifestyle5 out of ..."
289,3 BHK Flat in Sector 65 Gurgaon,sector 65,mm golfestate.,6.15,"₹ 15,998/sq.ft.",Carpet area: 3844 (357.12 sq.m.),3 Bedrooms,5 Bathrooms,3+ Balconies,Servant Room,"Duplex 3bhk, Sector 65 Gurgaon, Gurgaon, Haryana",1st of 14 Floors,West,1 to 5 Year Old,"['Sector 54 Chowk Metro Station', 'Sahara Mall...",3bhk flat/apartment for sale in m3m golf estat...,"['1 Water Purifier', '1 Fan', '1 Fridge', '1 E...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Connectivity5 out of 5', 'Management5 out of..."

In [67]:
df.drop(286, inplace=True)

    the area column name should be price per sq ft instead of area.
        1) so we will first make remvoe the sq/ft from the values and then make them numerical dtype
        2) also change the name of the column 'area' -> 'price_per_sqft'

In [68]:
df.rename(columns={'area':'price_per_sqft'},inplace=True)

In [69]:
df['price_per_sqft'] = df['price_per_sqft'].str.split('/').str.get(0).str.split(' ').str.get(1).str.replace(',','').astype(float)

    from price and price_per_sqft column i can find the area

In [70]:
area = round((df['price']/df['price_per_sqft'])*10000000,2)

In [71]:
df.insert(5, 'area', area)

In [72]:
df.head()

,property_name,sector,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,krishna colony,maa bhagwati residency,0.45,5000.0,900.0,Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,ashok vihar,apna enclave,0.5,7692.0,650.03,Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,sohna,tulsiani easy in homes,0.4,6722.0,595.06,Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,sector 61,smart world orchard,1.47,12250.0,1200.0,Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,2023-12-01 00:00:00,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,sector 92,parkwood westend,0.7,5204.0,1345.12,Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

**bedroom**<br>
    converting bedroom to numerical dtype by removing the Bedrooms string from the string

In [73]:
df['bedRoom'].value_counts()

bedRoom
3 Bedrooms    1439
2 Bedrooms     948
4 Bedrooms     481
1 Bedroom      105
5 Bedrooms      32
6 Bedrooms       3
Name: count, dtype: int64

In [74]:
df['bedRoom'] = df['bedRoom'].str.split(' ').str.get(0).str.strip().astype(float)

**bathroom**<br>
    removing the bathroom keyword from the string

In [75]:
df['bathroom'].value_counts()

bathroom
2 Bathrooms    1047
3 Bathrooms     991
4 Bathrooms     638
5 Bathrooms     170
1 Bathroom      115
6 Bathrooms      42
7 Bathrooms       5
Name: count, dtype: int64

In [76]:
df['bathroom'] = df['bathroom'].str.split(' ').str.get(0).str.strip().astype(float)

**balcony**<br>
    we can't convert it into a numerical value because there is a value '3+ Balconies'

In [77]:
df['balcony'].value_counts()

balcony
3 Balconies     977
3+ Balconies    863
2 Balconies     751
1 Balcony       318
No Balcony       99
Name: count, dtype: int64

In [78]:
df['balcony'] = df['balcony'].str.split(' ').str.get(0).str.strip()

    i am not able to get any useful information from the **address* column so i am going to remove it, but if later on if it is required then i will take the action

In [79]:
df.drop(columns=['address'], inplace=True)

**floorNum**<br>
    1) there are values like 'Ground', 'Lower Ground', 'Basement'. so i will replace them with their respective meanings in numerical form<br>
    2) for values like 20th of 28 floors i am going to take out only the '20' value from this because this is the thing buyer cares most about(on which floor, I am getting the flat)

In [80]:
df['floorNum'].value_counts()

floorNum
2nd   of 4 Floors           74
3rd   of 4 Floors           71
4th   of 4 Floors           63
1st   of 4 Floors           61
14th   of 14 Floors         50
12nd   of 14 Floors         49
Ground of 14 Floors         40
10th   of 14 Floors         35
7th   of 14 Floors          35
8th   of 14 Floors          34
4th   of 14 Floors          28
6th   of 14 Floors          27
3rd   of 3 Floors           26
2nd   of 2 Floors           26
1st   of 14 Floors          26
3rd   of 14 Floors          24
8th   of 19 Floors          24
5th   of 14 Floors          24
11st   of 14 Floors         23
1st   of 1 Floors           23
9th   of 9 Floors           23
9th   of 14 Floors          23
2nd   of 3 Floors           22
5th   of 12 Floors          22
2nd   of 14 Floors          21
8th   of 18 Floors          20
Ground of 1 Floors          18
7th   of 18 Floors          18
6th   of 18 Floors          18
10th   of 19 Floors         18
12nd   of 12 Floors         17
10th   of 18 Floors         17
9th   of 13 Floors          17
7th   of 15 Floors          17
5th   of 15 Floors          16
3rd   of 18 Floors          16
1st   of 3 Floors           15
9th   of 15 Floors          15
2nd   of 12 Floors          15
6th   of 12 Floors          15
6th   of 19 Floors          14
6th   of 10 Floors          13
Ground of 4 Floors          13
7th   of 7 Floors           13
1st   of 2 Floors           13
5th   of 5 Floors           13
10th   of 26 Floors         13
3rd   of 13 Floors          13
10th   of 10 Floors         12
6th   of 15 Floors          12
4th   of 13 Floors          11
8th   of 12 Floors          11
8th   of 8 Floors           11
4th   of 10 Floors          11
6th   of 6 Floors           11
17th   of 17 Floors         11
9th   of 26 Floors          11
15th   of 19 Floors         11
11st   of 18 Floors         11
9th   of 24 Floors          11
16th   of 19 Floors         11
4th   of 15 Floors          10
4th   of 12 Floors          10
3rd   of 5 Floors           10
2nd   of 19 Floors          10
7th   of 26 Floors          10
3rd   of 9 Floors           10
10th   of 12 Floors         10
1st   of 26 Floors          10
12nd   of 18 Floors         10
7th   of 21 Floors          10
7th   of 13 Floors          10
6th   of 13 Floors          10
12nd   of 17 Floors          9
5th   of 18 Floors           9
9th   of 20 Floors           9
8th   of 22 Floors           9
18th   of 19 Floors          9
13rd   of 14 Floors          9
8th   of 15 Floors           9
3rd   of 15 Floors           9
3rd   of 12 Floors           9
14th   of 15 Floors          9
6th   of 16 Floors           9
6th   of 26 Floors           9
7th   of 12 Floors           9
7th   of 17 Floors           9
15th   of 29 Floors          9
14th   of 19 Floors          9
13rd   of 13 Floors          8
1st   of 19 Floors           8
9th   of 12 Floors           8
8th   of 13 Floors           8
2nd   of 5 Floors            8
14th   of 24 Floors          8
3rd   of 19 Floors           8
10th   of 17 Floors          8
2nd   of 15 Floors           8
8th   of 26 Floors           8
5th   of 9 Floors            8
2nd   of 8 Floors            8
4th   of 26 Floors           8
12nd   of 19 Floors          8
12nd   of 26 Floors          8
10th   of 13 Floors          8
12nd   of 24 Floors          8
8th   of 24 Floors           8
9th   of 18 Floors           8
5th   of 13 Floors           8
12nd   of 13 Floors          7
7th   of 19 Floors           7
5th   of 20 Floors           7
11st   of 11 Floors          7
11st   of 13 Floors          7
1st   of 13 Floors           7
2nd   of 17 Floors           7
16th   of 16 Floors          7
8th   of 10 Floors           7
Ground of 3 Floors           7
15th   of 15 Floors          7
11st   of 26 Floors          7
2nd   of 10 Floors           7
9th   of 19 Floors           7
8th   of 21 Floors           7
5th   of 29 Floors           7
10th   of 21 Floors          7
12nd   of 15 Floors          7
11st   of 24 Floors          7
2nd   of 13 Floors           7
4th   of 19 Floors           7
5th   of 25 Floors           6
14th   of 27 Floors          6
11st   of 12 Floors          6
16th   of 18 Floors          6
7th   of 20 Floors           6
10th   of 20 Floors          6
19th   of 19 Floors          6
4th   of 18 Floors           6
1st   of 10 Floors           6
12nd   of 22 Floors          6
17th   of 19 Floors          6
Ground of 16 Floors          6
10th   of 15 Floors          6
2nd   of 20 Floors           6
5th   of 22 Floors           6
10th   of 29 Floors          6
5th   of 10 Floors           6
6th   of 9 Floors            6
3rd   of 25 Floors           6
Ground of 15 Floors          6
4th   of 17 Floors           6
1st   of 5 Floors            6
11st   of 19 Floors          6
5th   of 8 Floors            5
3rd   of 20 Floors           5
10th   of 25 Floors          5
14th   of 17 Floors          5
9th   of 30 Floors           5
6th   of 20 Floors           5
11st   of 25 Floors          5
1st   of 15 Floors           5
1st   of 12 Floors           5
11st   of 30 Floors          5
1st   of 7 Floors            5
5th   of 19 Floors           5
9th   of 22 Floors           5
6th   of 17 Floors           5
4th   of 22 Floors           5
14th   of 29 Floors          5
7th   of 27 Floors           5
15th   of 28 Floors          5
17th   of 24 Floors          5
12nd   of 29 Floors          5
11st   of 16 Floors          5
11st   of 29 Floors          5
Ground of 21 Floors          5
10th   of 24 Floors          5
Ground of 12 Floors          5
15th   of 21 Floors          5
10th   of 27 Floors          5
15th   of 18 Floors          5
7th   of 8 Floors            5
8th   of 9 Floors            5
18th   of 29 Floors          5
8th   of 30 Floors           5
16th   of 26 Floors          5
12nd   of 21 Floors          5
6th   of 11 Floors           5
4th   of 9 Floors            5
Ground of 19 Floors          5
4th   of 27 Floors           5
14th   of 16 Floors          5
9th   of 11 Floors           5
25th   of 25 Floors          4
20th   of 20 Floors          4
18th   of 32 Floors          4
1st   of 18 Floors           4
3rd   of 11 Floors           4
23rd   of 26 Floors          4
4th   of 8 Floors            4
12nd   of 16 Floors          4
11st   of 15 Floors          4
2nd   of 16 Floors           4
9th   of 10 Floors           4
7th   of 9 Floors            4
22nd   of 24 Floors          4
19th   of 40 Floors          4
15th   of 32 Floors          4
14th   of 18 Floors          4
14th   of 21 Floors          4
7th   of 10 Floors           4
19th   of 24 Floors          4
11st   of 20 Floors          4
11st   of 17 Floors          4
17th   of 25 Floors          4
8th   of 16 Floors           4
20th   of 26 Floors          4
12nd   of 30 Floors          4
5th   of 16 Floors           4
22nd   of 30 Floors          4
2nd   of 9 Floors            4
15th   of 25 Floors          4
14th   of 26 Floors          4
17th   of 18 Floors          4
6th   of 30 Floors           4
Ground of 13 Floors          4
5th   of 24 Floors           4
15th   of 26 Floors          4
2nd   of 11 Floors           4
8th   of 20 Floors           4
15th   of 16 Floors          4
17th   of 26 Floors          4
13rd   of 25 Floors          4
7th   of 24 Floors           4
5th   of 23 Floors           4
Ground of 17 Floors          4
15th   of 23 Floors          4
7th   of 11 Floors           4
13rd   of 19 Floors          4
13rd   of 21 Floors          4
3rd   of 22 Floors           4
3rd   of 17 Floors           4
3rd   of 10 Floors           4
5th   of 17 Floors           3
21st   of 24 Floors          3
6th   of 24 Floors           3
1st   of 25 Floors           3
3rd   of 26 Floors           3
1st   of 11 Floors           3
15th   of 20 Floors          3
10th   of 16 Floors          3
1st   of 35 Floors           3
30th   of 32 Floors          3
8th   of 25 Floors           3
31st   of 32 Floors          3
18th   of 18 Floors          3
9th   of 16 Floors           3
26th   of 30 Floors          3
16th   of 20 Floors          3
3rd   of 8 Floors            3
7th   of 23 Floors           3
10th   of 30 Floors          3
5th   of 30 Floors           3
15th   of 40 Floors          3
8th   of 11 Floors           3
18th   of 30 Floors          3
5th   of 26 Floors           3
Ground of 18 Floors          3
9th   of 21 Floors           3
19th   of 29 Floors          3
6th   of 8 Floors            3
15th   of 39 Floors          3
8th   of 40 Floors           3
2nd   of 26 Floors           3
12nd   of 23 Floors          3
10th   of 28 Floors          3
3rd   of 16 Floors           3
4th   of 20 Floors           3
17th   of 30 Floors          3
17th   of 29 Floors          3
19th   of 30 Floors          3
6th   of 29 Floors           3
17th   of 20 Floors          3
11st   of 27 Floors          3
27th   of 27 Floors          3
4th   of 21 Floors           3
14th   of 32 Floors          3
10th   of 23 Floors          3
2nd   of 22 Floors           3
24th   of 24 Floors          3
21st   of 22 Floors          3
4th   of 16 Floors           3
4th   of 29 Floors           3
19th   of 21 Floors          3
6th   of 21 Floors           3
8th   of 17 Floors           3
20th   of 28 Floors          3
Ground of 26 Floors          3
12nd   of 27 Floors          3
6th   of 22 Floors           3
6th   of 23 Floors           3
9th   of 40 Floors           3
18th   of 26 Floors          3
15th   of 22 Floors          3
13rd   of 15 Floors          3
23rd   of 23 Floors          3
9th   of 29 Floors           2
43   of 47 Floors            2
2nd   of 25 Floors           2
20th   of 22 Floors          2
11st   of 21 Floors          2
4th   of 34 Floors           2
Lower Ground of 4 Floors     2
10th   of 22 Floors          2
8th   of 34 Floors           2
1st   of 22 Floors           2
8th   of 32 Floors           2
39th   of 40 Floors          2
14th   of 20 Floors          2
20th   of 23 Floors          2
9th   of 17 Floors           2
2nd   of 24 Floors           2
16th   of 24 Floors          2
19th   of 20 Floors          2
Ground of 23 Floors          2
4th   of 11 Floors           2
18th   of 21 Floors          2
14th   of 28 Floors          2
16th   of 27 Floors          2
16th   of 32 Floors          2
8th   of 29 Floors           2
3rd   of 32 Floors           2
7th   of 29 Floors           2
16th   of 21 Floors          2
25th   of 30 Floors          2
9th   of 28 Floors           2
13rd   of 40 Floors          2
6th   of 31 Floors           2
1st   of 24 Floors           2
12nd   of 25 Floors          2
4th   of 5 Floors            2
7th   of 16 Floors           2
28th   of 30 Floors          2
Ground of 51 Floors          2
10th   of 32 Floors          2
7th   of 36 Floors           2
3rd   of 29 Floors           2
3rd   of 27 Floors           2
10th   of 11 Floors          2
2nd   of 21 Floors           2
8th   of 28 Floors           2
15th   of 17 Floors          2
20th   of 25 Floors          2
7th   of 22 Floors           2
2nd   of 40 Floors           2
9th   of 27 Floors           2
21st   of 27 Floors          2
2nd   of 32 Floors           2
18th   of 24 Floors          2
23rd   of 34 Floors          2
1st   of 8 Floors            2
1st   of 20 Floors           2
1st   of 30 Floors           2
22nd   of 25 Floors          2
2nd   of 7 Floors            2
2nd   of 18 Floors           2
3rd   of 24 Floors           2
16th   of 34 Floors          2
17th   of 23 Floors          2
4th   of 7 Floors            2
15th   of 24 Floors          2
16th   of 30 Floors          2
23rd   of 29 Floors          2
25th   of 29 Floors          2
11st   of 23 Floors          2
8th   of 23 Floors           2
19th   of 27 Floors          2
10th   of 40 Floors          2
13rd   of 30 Floors          2
7th   of 30 Floors           2
13rd   of 20 Floors          2
27th   of 29 Floors          2
15th   of 31 Floors          2
2nd   of 28 Floors           2
2nd   of 6 Floors            2
24th   of 30 Floors          2
16th   of 36 Floors          2
5th   of 11 Floors           2
1st   of 16 Floors           2
1st   of 17 Floors           2
3rd   of 33 Floors           2
17th   of 33 Floors          2
15th   of 45 Floors          2
40th   of 40 Floors          2
31st   of 40 Floors          1
11st   of 22 Floors          1
Ground of 11 Floors          1
29th   of 31 Floors          1
21st   of 41 Floors          1
32nd   of 32 Floors          1
32nd   of 55 Floors          1
20th   of 32 Floors          1
Basement of 28 Floors        1
19th   of 41 Floors          1
20th   of 34 Floors          1
16th   of 22 Floors          1
18th   of 25 Floors          1
23rd   of 28 Floors          1
11st   of 36 Floors          1
28th   of 28 Floors          1
Basement of 4 Floors         1
2nd   of 34 Floors           1
4th   of 40 Floors           1
20th   of 47 Floors          1
27th   of 48 Floors          1
6th   of 7 Floors            1
33rd   of 48 Floors          1
35th   of 35 Floors          1
26th   of 47 Floors          1
Ground of 24 Floors          1
7th   of 25 Floors           1
8th   of 42 Floors           1
26th   of 34 Floors          1
21st   of 29 Floors          1
14th   of 22 Floors          1
33rd   of 42 Floors          1
1st   of 44 Floors           1
24th   of 31 Floors          1
24th   of 51 Floors          1
2nd   of 36 Floors           1
19th   of 31 Floors          1
16th   of 51 Floors          1
25th   of 36 Floors          1
21st   of 28 Floors          1
7th   of 42 Floors           1
10th   of 51 Floors          1
15th   of 30 Floors          1
3rd   of 6 Floors            1
20th   of 40 Floors          1
9th   of 42 Floors           1
8th   of 31 Floors           1
20th   of 30 Floors          1
18th   of 51 Floors          1
24th   of 27 Floors          1
19th   of 22 Floors          1
19th   of 26 Floors          1
2nd   of 27 Floors           1
14th   of 51 Floors          1
19th   of 39 Floors          1
12nd   of 39 Floors          1
38th   of 40 Floors          1
18th   of 40 Floors          1
35th   of 51 Floors          1
22nd   of 28 Floors          1
17th   of 21 Floors          1
4th   of 39 Floors           1
24th   of 32 Floors          1
8th   of 27 Floors           1
28th   of 29 Floors          1
15th   of 27 Floors          1
3rd   of 40 Floors           1
6th   of 25 Floors           1
16th   of 25 Floors          1
4th   of 28 Floors           1
7th   of 32 Floors           1
30th   of 40 Floors          1
4th   of 25 Floors           1
19th   of 23 Floors          1
5th   of 27 Floors           1
24th   of 39 Floors          1
20th   of 43 Floors          1
21st   of 51 Floors          1
12nd   of 28 Floors          1
10th   of 34 Floors          1
18th   of 23 Floors          1
12nd   of 32 Floors          1
23rd   of 40 Floors          1
5th   of 32 Floors           1
1st   of 9 Floors            1
20th   of 29 Floors          1
13rd   of 18 Floors          1
7th   of 34 Floors           1
10th   of 39 Floors          1
21st   of 26 Floors          1
22nd   of 40 Floors          1
16th   of 41 Floors          1
7th   of 40 Floors           1
12nd   of 40 Floors          1
3rd   of 28 Floors           1
17th   of 28 Floors          1
3rd   of 30 Floors           1
29th   of 29 Floors          1
16th   of 31 Floors          1
5th   of 21 Floors           1
12nd   of 34 Floors          1
5th   of 34 Floors           1
9th   of 25 Floors           1
45   of 47 Floors            1
Ground of 25 Floors          1
9th   of 23 Floors           1
33rd   of 33 Floors          1
1st   of 6 Floors            1
20th   of 24 Floors          1
13rd   of 17 Floors          1
Ground of 6 Floors           1
Basement of 13 Floors        1
18th   of 22 Floors          1
17th   of 22 Floors          1
24th   of 36 Floors          1
3rd   of 36 Floors           1
5th   of 6 Floors            1
8th   of 35 Floors           1
Lower Ground of 1 Floors     1
5th   of 35 Floors           1
Ground of 2 Floors           1
10th   of 33 Floors          1
18th   of 35 Floors          1
17th   of 31 Floors          1
21st   of 23 Floors          1
Ground of 5 Floors           1
Ground of 40 Floors          1
13rd   of 22 Floors          1
16th   of 35 Floors          1
44   of 47 Floors            1
23rd   of 24 Floors          1
17th   of 47 Floors          1
4th   of 6 Floors            1
30th   of 34 Floors          1
13rd   of 47 Floors          1
34th   of 42 Floors          1
29th   of 39 Floors          1
18th   of 20 Floors          1
3rd   of 31 Floors           1
27th   of 30 Floors          1
34th   of 34 Floors          1
5th   of 36 Floors           1
19th   of 32 Floors          1
16th   of 45 Floors          1
22nd   of 23 Floors          1
7th   of 28 Floors           1
21st   of 36 Floors          1
14th   of 41 Floors          1
Ground of 29 Floors          1
22nd   of 26 Floors          1
13rd   of 26 Floors          1
14th   of 25 Floors          1
3rd   of 7 Floors            1
Ground of 22 Floors          1
13rd   of 34 Floors          1
23rd   of 36 Floors          1
Name: count, dtype: int64

    i am creating a copy for my dataframe so that if there is any trouble i can come back to my real dataframe

In [81]:
df1 = df.copy()

In [82]:
df1['floorNum'] = df1['floorNum'].str.split('of').str.get(0).str.replace('Lower Ground', '-1').str.replace('Ground', '0').str.replace('Basement', '-1')

now lets remove the 'nd' from '2nd' etc...

In [83]:
df1['floorNum'].value_counts()

floorNum
2nd        258
3rd        249
1st        220
4th        204
8th        200
7th        189
10th       185
6th        185
5th        172
9th        171
12nd       160
0          132
14th       120
11st       115
15th        84
16th        53
17th        52
13rd        44
18th        38
19th        34
20th        25
21st        15
23rd        15
22nd        14
24th        11
25th         9
27th         7
-1           6
30th         5
26th         5
31st         4
28th         4
29th         3
33rd         3
32nd         2
43           2
35th         2
39th         2
34th         2
40th         2
38th         1
45           1
44           1
Name: count, dtype: int64

In [84]:
df1['floorNum'] = df1['floorNum'].str.extract(r'(-?\d+)')

here we can clearly see that for the given indexes values for all the columns except 'property_name', 'sector', 'society' is not available. so we will remove these indexes because i can't predict values for these many columns

In [85]:
df1[df1['bedRoom'].isnull()]

,property_name,sector,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
2850,2 BHK Flat in Sector 107 Gurgaon,sector 107,signature global solera.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2851,4 BHK Flat in Sector 53 Gurgaon,sector 53,tulip monsella,NaN,33198.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2852,2 BHK Flat in New Palam Vihar,new palam vihar,my home,NaN,4400.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2853,2 BHK Flat in Sohna,sohna,breez global hill view,NaN,5470.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2923,3 BHK Flat in Sector 99A Gurgaon,sector 99a,pareena coban residences,NaN,5759.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2924,1 BHK Flat in Golf Course Ext Road,golf course ext road,ikon tower baani city centre,NaN,12437.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2925,2 BHK Flat in Sector 89 Gurgaon,sector 89,greenopolis,NaN,4820.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2927,4 BHK Flat in C Block Sushant Lok Phase 1,c block sushant lok phase 1,maple heights,NaN,8888.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2928,2 BHK Flat in Sector 99 Gurgaon,sector 99,assotech blith,NaN,6593.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2994,4 BHK Flat in DLF Phase 4,dlf phase 4,chanderlok society,NaN,7234.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2995,3 BHK Flat in Sector 9A Gurgaon,sector 9a,jammu and kashmir bank employees cghs.,NaN,6129.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2996,3 BHK Flat in Sector 37C Gurgaon,sector 37c,ild greens.,NaN,4723.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2997,3 BHK Flat in Adarsh Nagar,adarsh nagar,ss residency,NaN,4818.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2998,3 BHK Flat in Rajendra Park,rajendra park,uphar lakshya homes,NaN,4200.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2999,2 BHK Flat in Sector 79 Gurgaon,sector 79,supertech araville,NaN,9000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3000,3 BHK Flat in Sector 37C Gurgaon,sector 37c,corona optus.,NaN,6361.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3001,3 BHK Flat in Sector 78 Gurgaon,sector 78,umang monsoon breeze,NaN,6493.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3002,3 BHK Flat in Sector 88A Gurgaon,sector 88a,godrej oasis.,NaN,8108.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3003,"2 BHK Flat in Godrej Aria , sector 79 , Gurgaon","godrej aria , sector 79 ,","godrej aria , sector , gurgaon",NaN,11111.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [86]:
df1.drop(index=df1[df1['bedRoom'].isnull()].index, inplace=True)

In [87]:
df1.insert(1, 'property_type', 'flat')

In [88]:
df1.to_csv('flat_cleaned.csv',index=False)