#   Gurgaon Data Preprocessing(independent_house)

## 1.1 Introduction and Setup
In this phase we will first import the raw and scraped data for the gurgaon independent house and perform an analysis. To analyse we will first import required libraries and load our dataset in the pandas dataframe to know what we are working with.

In [122]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [123]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [124]:
df = pd.read_excel('C:\\capstone_project_dscience\\real_estate_project\\dataset\\independent-house.xlsx')

## 1.2 High Level Data Inspection
here we will see what are the dimensions of our dataset, how many attributes are there, attributes name and spot any missing values

In [125]:
df.head()

,property_name,link,society,price,rate,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
0,5 Bedroom House for sale in Sector 70A Gurgaon,https://www.99acres.com/5-bhk-bedroom-independ...,Bptp Visionnaire,5.25 Crore,"₹ 20,115/sq.ft.",(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5...",K70037724
1,5 Bedroom House for sale in Sector 21A Faridabad,https://www.99acres.com/5-bhk-bedroom-independ...,NaN,5.7 Crore,"₹ 105,751/sq.ft.",(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5 Bedrooms,4 Bathrooms,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN,E69288322
2,10 Bedroom House for sale in Sushant Lok Phase 1,https://www.99acres.com/10-bhk-bedroom-indepen...,NaN,2.1 Crore,"₹ 38,251/sq.ft.",(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10 Bedrooms,10 Bathrooms,3+ Balconies,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5...",F69536898
3,21 Bedroom House for sale in Sector 54 Gurgaon,https://www.99acres.com/21-bhk-bedroom-indepen...,NaN,5 Crore,"₹ 43,066/sq.ft.",(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21 Bedrooms,21 Bathrooms,3+ Balconies,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5...",R69483164
4,12 Bedroom House for sale in Sushant Lok Phase 1,https://www.99acres.com/12-bhk-bedroom-indepen...,NaN,3 Crore,"₹ 53,763/sq.ft.",(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12 Bedrooms,12 Bathrooms,3+ Balconies,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5...",M69381272

In [126]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1095 entries, 0 to 1094
Data columns (total 21 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    1095 non-null   str
 1   link             1095 non-null   str
 2   society          471 non-null    str
 3   price            968 non-null    str
 4   rate             1054 non-null   str
 5   area             1095 non-null   str
 6   areaWithType     987 non-null    str
 7   bedRoom          987 non-null    str
 8   bathroom         987 non-null    str
 9   balcony          987 non-null    str
 10  additionalRoom   589 non-null    str
 11  address          1031 non-null   str
 12  noOfFloor        967 non-null    str
 13  facing           674 non-null    str
 14  agePossession    987 non-null    object
 15  nearbyLocations  913 non-null    str
 16  description      1036 non-null   str
 17  furnishDetails   743 non-null    str
 18  features         674 non-null    str
 19  rating           907 non-null    str
 20  property_id      1036 non-null   str
dtypes: object(1), str(20)
memory usage: 179.8+ KB

### 1.2.1 column dtype
        1) columns like price and area they are of string type instead of numerical values
        2) columns like 'link' and 'property_id' are of no use

In [127]:
df.drop(columns=['link','property_id'], inplace=True)

### 1.2.2 dataset shape
        1)number of rows in the dataset is 3028
        2) number of columns -> 20

In [128]:
df.shape

(1095, 19)

## 1.3 cleaning and feature extraction
        property_name column
            1) i want to extract the sector name from the property_name column

In [129]:
df['property_name'].value_counts()

property_name
4 Bedroom House for sale in Sector 109 Gurgaon                                           25
4 Bedroom House for sale in Sector 48 Gurgaon                                            22
5 Bedroom House for sale in Sector 109 Gurgaon                                           17
5 Bedroom House for sale in DLF Phase 1                                                  16
5 Bedroom House for sale in DLF Phase 2                                                  16
5 Bedroom House for sale in Sector 66 Gurgaon                                            14
4 Bedroom House for sale in Nirvana Country                                              14
4 Bedroom House for sale in Sector 66 Gurgaon                                            12
5 Bedroom House for sale in Nirvana Country                                              10
5 Bedroom House for sale in Sector 33 Gurgaon                                            10
4 Bedroom House for sale in DLF Phase 1                                                   9
4 Bedroom House for sale in Sector 70A Gurgaon                                            8
3 Bedroom House for sale in Sector 48 Gurgaon                                             8
6 Bedroom House for sale in DLF Phase 1                                                   8
4 Bedroom House for sale in Palam Vihar                                                   8
9 Bedroom House for sale in DLF Phase 2                                                   7
3 Bedroom House for sale in Nirvana Country                                               7
3 Bedroom House for sale in Laxman Vihar                                                  7
6 Bedroom House for sale in Uppals Southend                                               6
4 Bedroom House for sale in Sushant Lok Phase 3                                           6
3 Bedroom House for sale in Sector 109 Gurgaon                                            6
4 Bedroom House for sale in Sector 82 Gurgaon                                             6
3 Bedroom House for sale in Rajendra Park                                                 6
2 Bedroom House for sale in Laxman Vihar                                                  6
5 Bedroom House for sale in Laxman Vihar                                                  6
4 Bedroom House for sale in DLF Phase 3                                                   6
4 Bedroom House for sale in DLF Phase 2                                                   5
4 Bedroom House for sale in Sector 112 Gurgaon                                            5
4 Bedroom House for sale in Sector 86 Gurgaon                                             5
6 Bedroom House for sale in Sushant Lok Phase 3                                           5
4 Bedroom House for sale in DLF Phase 4                                                   5
5 Bedroom House for sale in Sector 14 Gurgaon                                             5
5 Bedroom House for sale in Sector 48 Gurgaon                                             5
3 Bedroom House for sale in Sector 49 Gurgaon                                             5
16 Bedroom House for sale in DLF Phase 1                                                  4
6 Bedroom House for sale in DLF Phase 2                                                   4
5 Bedroom House for sale in Sushant Lok Phase 1                                           4
3 Bedroom House for sale in Palam Vihar                                                   4
3 Bedroom House for sale in Sector 4 Gurgaon                                              4
3 Bedroom House for sale in Laxman Vihar Phase 2                                          4
2 Bedroom House for sale in Laxman Vihar Phase 2                                          4
4 Bedroom House for sale in Sector 31 Gurgaon                                             4
8 Bedroom House for sale in DLF Phase 3                                                   4
6 Bedroom House for sale in Palam Vihar                                                   4
3 Bedroom House for sale in Sector 14 Gurgaon                                             4
2 Bedroom House for sale in Palam Vihar Extension                                         4
4 Bedroom House for sale in Sector 54 Gurgaon                                             4
12 Bedroom House for sale in DLF Phase 1                                                  4
4 Bedroom House for sale in Sector 26 Gurgaon                                             4
3 Bedroom House for sale in Sushant Lok Phase 1                                           3
12 Bedroom House for sale in DLF Phase 2                                                  3
12 Bedroom House for sale in Sector 56 Gurgaon                                            3
4 Bedroom House for sale in C Block Sushant Lok Phase 1                                   3
8 Bedroom House for sale in Palam Vihar                                                   3
5 Bedroom House for sale in Greenwood City                                                3
4 Bedroom House for sale in Sector 55 Gurgaon                                             3
4 Bedroom House for sale in Sector 91 Gurgaon                                             3
5 Bedroom House for sale in Sector 111 Gurgaon                                            3
3 Bedroom House for sale in Sector 73 Gurgaon                                             3
7 Bedroom House for sale in Sector 109 Gurgaon                                            3
7 Bedroom House for sale in Sushant Lok Phase 1                                           3
1 Bedroom House for sale in Sushant Lok Phase 1                                           3
5 Bedroom House for sale in Palam Vihar                                                   3
3 Bedroom House for sale in Ashok Vihar                                                   3
4 Bedroom House for sale in Sector 92 Gurgaon                                             3
5 Bedroom House for sale in Sector 72 Gurgaon                                             3
5 Bedroom House for sale in Jyoti Park                                                    3
10 Bedroom House for sale in Rajiv Nagar                                                  3
5 Bedroom House for sale in Sector 50 Gurgaon                                             3
2 Bedroom House for sale in Ashok Vihar Phase 3 Extension                                 3
3 Bedroom House for sale in Sector 38 Gurgaon                                             3
4 Bedroom House for sale in Laxman Vihar Phase 2                                          3
6 Bedroom House for sale in Sector 17 Gurgaon                                             3
1 Bedroom House for sale in Sector 3A Gurgaon                                             3
3 Bedroom House for sale in Sector 70A Gurgaon                                            3
3 Bedroom House for sale in Ansal Plaza                                                   3
4 Bedroom House for sale in Sector 103 Gurgaon                                            3
5 Bedroom House for sale in Mianwali Colony                                               3
5 Bedroom House for sale in New Colony                                                    3
6 Bedroom House for sale in Sector 33 Gurgaon                                             3
1 Bedroom House for sale in Sector 39 Gurgaon                                             3
3 Bedroom House for sale in Sohna Road                                                    3
5 Bedroom House for sale in Uppals Southend                                               3
4 Bedroom House for sale in Sector 17B Gurgaon                                            3
12 Bedroom House for sale in Uppals Southend                                              3
3 Bedroom House for sale in Sector 82 Gurgaon                                             3
6 Bedroom House for sale in Greenwood City                                                3
8 Bedroom House for sale in Sector 46 Gurgaon                                             3
4 Bedroom House for sale in Sushant Lok Phase 1                                           3
5 Bedroom House for sale in Sector 57 Gurgaon                                             3
4 Bedroom House for sale in Sector 46 Gurgaon                                             3
7 Bedroom House for sale in Sector 48 Gurgaon                                             3
5 Bedroom House for sale in Sector 46 Gurgaon                                             3
3 Bedroom House for sale in Bissar                                                        3
5 Bedroom House for sale in Sector 70A Gurgaon                                            2
12 Bedroom House for sale in Sushant Lok Phase 1                                          2
6 Bedroom House for sale in DLF Phase 4                                                   2
5 Bedroom House for sale in B Block Sushant Lok Phase 1                                   2
9 Bedroom House for sale in Sector 9 Gurgaon                                              2
9 Bedroom House for sale in Sector 40 Gurgaon                                             2
4 Bedroom House for sale in Sector 67 Gurgaon                                             2
2 Bedroom House for sale in Sector 7 Gurgaon                                              2
2 Bedroom House for sale in Narsinghpur                                                   2
8 Bedroom House for sale in B1 Block Sector 57 Gurgaon                                    2
8 Bedroom House for sale in Uppals Southend                                               2
4 Bedroom House for sale in Malibu Town                                                   2
3 Bedroom House for sale in South City 1                                                  2
3 Bedroom House for sale in Sector 40 Gurgaon                                             2
12 Bedroom House for sale in Sector 40 Gurgaon                                            2
4 Bedroom House for sale in Sector 23 Gurgaon                                             2
4 Bedroom House for sale in Sector 72 Gurgaon                                             2
3 Bedroom House for sale in Sector 63A Gurgaon                                            2
4 Bedroom House for sale in Sector 65 Gurgaon                                             2
4 Bedroom House for sale in Sector-33 Sohna                                               2
3 Bedroom House for sale in Sector 7 Gurgaon                                              2
5 Bedroom House for sale in Sector 56 Gurgaon                                             2
6 Bedroom House for sale in Sushant Lok Phase 1                                           2
4 Bedroom House for sale in Sector 81 Gurgaon                                             2
5 Bedroom House for sale in Sector 23 Gurgaon                                             2
4 Bedroom House for sale in Madanpuri                                                     2
7 Bedroom House for sale in Sector 11 Gurgaon                                             2
5 Bedroom House for sale in Shivaji Nagar                                                 2
3 Bedroom House for sale in Hira Nagar                                                    2
19 Bedroom House for sale in Sector 17A Gurgaon                                           2
4 Bedroom House for sale in Sector 56 Gurgaon                                             2
7 Bedroom House for sale in DLF Phase 3                                                   2
5 Bedroom House for sale in Sohna Road                                                    2
2 Bedroom House for sale in Daulatabad                                                    2
2 Bedroom House for sale in Vishnu Garden                                                 2
10 Bedroom House for sale in Shivpuri                                                     2
2 Bedroom House for sale in New Palam Vihar                                               2
8 Bedroom House for sale in Sector 56 Gurgaon                                             2
5 Bedroom House for sale in Sector 5 Gurgaon                                              2
4 Bedroom House for sale in Rajendra Park                                                 2
2 Bedroom House for sale in Sector 5 Gurgaon                                              2
3 Bedroom House for sale in Devilal Colony                                                2
1 Bedroom House for sale in Ashok Vihar Phase 3 Extension                                 2
7 Bedroom House for sale in Rajendra Park                                                 2
3 Bedroom House for sale in Sushant Lok Phase 3                                           2
2 Bedroom House for sale in Devilal Colony                                                2
1 Bedroom House for sale in Mianwali Colony                                               2
2 Bedroom House for sale in Sector 8 Gurgaon                                              2
3 Bedroom House for sale in Dharam Colony                                                 2
4 Bedroom House for sale in Saraswati Vihar                                               2
2 Bedroom House for sale in Sector 56 Gurgaon                                             2
12 Bedroom House for sale in Malibu Town                                                  2
9 Bedroom House for sale in C Block Sushant Lok Phase 1                                   2
5 Bedroom House for sale in Bhim Nagar                                                    2
4 Bedroom House for sale in Laxman Vihar                                                  2
2 Bedroom House for sale in Baldev Nagar                                                  2
3 Bedroom House for sale in Arjun Nagar                                                   2
3 Bedroom House for sale in DLF Phase 2                                                   2
2 Bedroom House for sale in Garhi Harsaru                                                 2
4 Bedroom House for sale in Sector 1 Gurgaon                                              2
4 Bedroom House for sale in Sector 10A Gurgaon                                            2
4 Bedroom House for sale in Arjun Nagar                                                   2
3 Bedroom House for sale in Baldev Nagar                                                  2
2 Bedroom House for sale in Sheetla Colony                                                2
5 Bedroom House for sale in Sector 39 Gurgaon                                             2
9 Bedroom House for sale in Palam Vihar                                                   2
4 Bedroom House for sale in Sector 3 Gurgaon                                              2
4 Bedroom House for sale in Sector 6 Gurgaon                                              2
5 Bedroom House for sale in Ashok Vihar Phase 2                                           2
5 Bedroom House for sale in Sector 108 Gurgaon                                            2
5 Bedroom House for sale in Sector 53 Gurgaon                                             2
5 Bedroom House for sale in Sector 3 Gurgaon                                              2
2 Bedroom House for sale in Sector 31 Gurgaon                                             2
6 Bedroom House for sale in Rajendra Park                                                 2
1 Bedroom House for sale in Laxman Vihar                                                  2
6 Bedroom House for sale in Sector 50 Gurgaon                                             2
2 Bedroom House for sale in Sohna                                                         2
4 Bedroom House for sale in Jacobpura                                                     2
5 Bedroom House for sale in Sector 7 Gurgaon                                              2
9 Bedroom House for sale in Palam Vihar Extension                                         2
5 Bedroom House for sale in Sector 11 Gurgaon                                             2
2 Bedroom House for sale in Sector 92 Gurgaon                                             2
2 Bedroom House for sale in Rajendra Park                                                 2
2 Bedroom House for sale in Sohna Road                                                    2
5 Bedroom House for sale in DLF Phase 3                                                   2
8 Bedroom House for sale in C Block Sushant Lok Phase 1                                   2
12 Bedroom House for sale in Sector 46 Gurgaon                                            2
9 Bedroom House for sale in Sector 45 Gurgaon                                             2
2 Bedroom House for sale in Sector-33 Sohna                                               2
3 Bedroom House for sale in Sushant Lok Phase 2                                           2
6 Bedroom House for sale in Sector 67 Gurgaon                                             2
3 Bedroom House for sale in Sector 23A Gurgaon                                            2
6 Bedroom House for sale in Sector 38 Gurgaon                                             2
8 Bedroom House for sale in Sushant Lok Phase 1                                           2
9 Bedroom House for sale in South City 1                                                  2
3 Bedroom House for sale in DLF Phase 1                                                   2
16 Bedroom House for sale in DLF Phase 4                                                  2
9 Bedroom House for sale in Sector 47 Gurgaon                                             2
6 Bedroom House for sale in Sector 22 Gurgaon                                             2
3 Bedroom House for sale in Rosewood                                                      2
10 Bedroom House for sale in South City 1                                                 2
4 Bedroom House for sale in Sector 4 Gurgaon                                              2
2 Bedroom House for sale in Sector 70A Gurgaon                                            2
10 Bedroom House for sale in DLF Phase 3                                                  2
7 Bedroom House for sale in DLF Phase 1                                                   2
6 Bedroom House for sale in Sector 14 Gurgaon                                             2
9 Bedroom House for sale in Sector 38 Gurgaon                                             2
3 Bedroom House for sale in Sector 26 Gurgaon                                             2
5 Bedroom House for sale in Sector 21A Faridabad                                          1
10 Bedroom House for sale in Sushant Lok Phase 1                                          1
21 Bedroom House for sale in Sector 54 Gurgaon                                            1
20 Bedroom House for sale in Sushant Lok Phase 1                                          1
13 Bedroom House for sale in DLF Phase 3                                                  1
6 Bedroom House for sale in New Palam Vihar Phase 1                                       1
7 Bedroom House for sale in Sector 38 Gurgaon                                             1
5 Bedroom House for sale in Sector 4 Gurgaon                                              1
10 Bedroom House for sale in DLF Phase 2                                                  1
4 Bedroom House for sale in Hsiidc Plot Sector 1 Imt Manesar                              1
3 Bedroom House for sale in Sector 15 Part 2                                              1
4 Bedroom House for sale in Sector 28 Gurgaon                                             1
12 Bedroom House for sale in Sector 55 Gurgaon                                            1
16 Bedroom House for sale in Sushant Lok Phase 1                                          1
16 Bedroom House for sale in Sector 56 Gurgaon                                            1

     here i extracted the sector detail from the property_name column

In [130]:
sectors = df['property_name'].str.split('in').str.get(1).str.split('Gurgaon').str.get(0).str.strip()

    created a new column for the sectors

In [131]:
df.insert(1, 'sector', sectors)

In [132]:
df.head()

,property_name,sector,society,price,rate,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,Sector 70A,Bptp Visionnaire,5.25 Crore,"₹ 20,115/sq.ft.",(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,Sector 21A Faridabad,NaN,5.7 Crore,"₹ 105,751/sq.ft.",(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5 Bedrooms,4 Bathrooms,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,Sushant Lok Phase 1,NaN,2.1 Crore,"₹ 38,251/sq.ft.",(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10 Bedrooms,10 Bathrooms,3+ Balconies,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,Sector 54,NaN,5 Crore,"₹ 43,066/sq.ft.",(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21 Bedrooms,21 Bathrooms,3+ Balconies,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,Sushant Lok Phase 1,NaN,3 Crore,"₹ 53,763/sq.ft.",(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12 Bedrooms,12 Bathrooms,3+ Balconies,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [133]:
df['sector'] = df['sector'].str.lower()

In [134]:
df['sector'].value_counts()

sector
sector 109                                                   51
dlf phase 1                                                  46
dlf phase 2                                                  40
sector 48                                                    39
nirvana country                                              32
sector 66                                                    27
sushant lok phase 1                                          26
laxman vihar                                                 25
palam vihar                                                  24
dlf phase 3                                                  19
sushant lok phase 3                                          16
sector 70a                                                   15
dlf phase 4                                                  15
uppals southend                                              15
sector 33                                                    15
sector 56                                                    14
rajendra park                                                14
sector 14                                                    13
laxman vihar phase 2                                         13
sector 46                                                    13
sector 38                                                    11
c block sushant lok phase 1                                  10
south city 1                                                 10
sector 82                                                    10
sector 31                                                    10
palam vihar extension                                         9
ashok vihar phase 3 extension                                 9
sohna road                                                    9
sector 7                                                      8
sector 54                                                     7
sector 4                                                      7
sector 40                                                     7
sector 55                                                     7
malibu town                                                   7
sector 57                                                     7
sector 3                                                      7
sohna                                                         7
rajiv nagar                                                   7
sector 50                                                     7
mianwali colony                                               7
sector 39                                                     7
sector 26                                                     7
sector 67                                                     6
greenwood city                                                6
sector 112                                                    6
sector 86                                                     6
new colony                                                    6
madanpuri                                                     6
sector 11                                                     6
jyoti park                                                    6
sector 5                                                      6
arjun nagar                                                   6
jacobpura                                                     6
ansal plaza                                                   6
sector 49                                                     6
sector 23                                                     5
sector 72                                                     5
shivaji nagar                                                 5
sector 81                                                     5
sector 8                                                      5
saraswati vihar                                               5
sector 92                                                     5
subhash nagar                                                 5
baldev nagar                                                  5
sector 3a                                                     5
surat nagar 1                                                 5
sushant lok phase 2                                           5
sector 9                                                      4
sector 73                                                     4
sector 63a                                                    4
sector-33 sohna                                               4
patel nagar                                                   4
maruti kunj                                                   4
vishnu garden                                                 4
shivpuri                                                      4
surya vihar                                                   4
devilal colony                                                4
bhim nagar                                                    4
ravi nagar                                                    4
sector 108                                                    4
garhi harsaru                                                 4
sector 10a                                                    4
sector 52                                                     4
sector 17                                                     4
sector 6                                                      4
ashok vihar phase 2                                           4
sector 103                                                    4
b block sushant lok phase 1                                   3
sector 91                                                     3
sector 111                                                    3
sector 63                                                     3
pratap nagar                                                  3
rajiv chowk                                                   3
dharam colony                                                 3
sector 17a                                                    3
ashok vihar                                                   3
laxmi garden                                                  3
new palam vihar                                               3
prem nagar                                                    3
surat nagar                                                   3
gandhi nagar                                                  3
sheetla colony                                                3
sector 105                                                    3
shakti nagar                                                  3
sector 37d                                                    3
bhondsi                                                       3
sector 1                                                      3
sector 12a                                                    3
                                                              3
sector 23a                                                    3
sector 47                                                     3
sector 17b                                                    3
a block sushant lok phase 1                                   3
sector 27                                                     3
sector 22                                                     3
bissar                                                        3
new palam vihar phase 1                                       2
sector 15 part 2                                              2
sector 28                                                     2
nars                                                          2
b1 block sector 57                                            2
sector 65                                                     2
krishna colony                                                2
hira nagar                                                    2
dayanand colony                                               2
mohan nagar                                                   2
daulatabad                                                    2
new basti                                                     2
manesar                                                       2
sector 76                                                     2
surat nagar phase 2                                           2
west rajiv nagar                                              2
farukhnagar                                                   2
acharya puri                                                  2
sector 13                                                     2
manohar nagar                                                 2
sector 53                                                     2
sector 89                                                     2
sector 69                                                     2
sector 45                                                     2
mayfield garden                                               2
rosewood                                                      2
suncity                                                       2
sector 21a faridabad                                          1
hsiidc plot sector 1 imt manesar                              1
sector 17c                                                    1
ghamroj                                                       1
sector 9a                                                     1
gopal nagar, garhi ghasita, sonipat                           1
jat colony,fazilpur/taj nagar road                            1
kheri                                                         1
sector 9b                                                     1
imt manesar                                                   1
bhora kalan                                                   1
near nand hospital                                            1
sector 93                                                     1
ashok vihar phase i                                           1
block h ashok vihar phase iii extension                       1
khandsa                                                       1
urban estate, sector 5                                        1
new palam vihar phase 2                                       1
near khandsa road                                             1
part 3 sector 5                                               1
lucknow                                                       1
pataudi road                                                  1
sector 70                                                     1
sector 12                                                     1
anand garden, sector-105 gurgaon                              1
dhunela                                                       1
heera nagar                                                   1
vir nagar                                                     1
sector 82a                                                    1
hno 13 sagar enclave sura                                     1
ram nagar                                                     1
block g sector-57                                             1
om nagar                                                      1
bhawani enclave                                               1
anand garden, sector-105                                      1
tekchand nagar                                                1
ashok vihar phase 3                                           1
dlf phase 5                                                   1
ansal's palam vihar                                           1
jacobpura near sadar bazar                                    1
sector 104                                                    1
shivji park colony                                            1
udyog vihar phase 1                                           1
mahalaxmi garden, rajendra place                              1
rattan garden                                                 1
sadar bazar                                                   1
naharpur rupa                                                 1
laxman vihar, railway road,                                   1
sector-5 sheetla colony                                       1
damdma                                                        1
new jyoti park                                                1
lajpat nagar                                                  1
mahavir pura                                                  1
sector 37b                                                    1
g block dlf city phase 1                                      1
park view                                                     1
dharam colony block e                                         1
ravi nager basai road                                         1
begampur khatola                                              1
dhankot                                                       1
sector 41                                                     1
sector 110                                                    1
devi lal colony gali no 12 gurgaon nr omkar public school     1
sector 36                                                     1
alipur                                                        1
sector 60                                                     1
sector 36 sohna                                               1
dwarka expressway                                             1
golf course road                                              1
saraswati enclave                                             1
sec 3 bhim vihar part 1 bhimgher kheri                        1
near euro                                                     1
bhimgarh kheri phase 3                                        1
huda saraswati vihar                                          1
sector 15                                                     1
sector 43                                                     1
laxmna vihar, phase 2                                         1
sector 51                                                     1
sector 67a                                                    1
sector 61                                                     1
mehrauli                                                      1
sector 42                                                     1
south city                                                    1
sector 83                                                     1
v block dlf phase 3                                           1
sector 15 part 1                                              1
sector 106                                                    1
Name: count, dtype: int64

***society column** <br>
        here in society column we can see that the some digits as well as characters are also attached with the names

In [135]:
df['society'].value_counts()

society
Vipul Tatvam Villa                                   27
Emaar MGF Marbella                                   26
International City by SOBHA Phase 2                  26
International City by Sobha Phase 1                  23
Unitech Uniworld Resorts                             14
DLF City Plots Phase 2                               11
Unitech Espace                                       11
DLF City Plots                                       11
Bptp Visionnaire                                      9
Uppal Southend4.0 ★                                   9
Eldeco Mansionz                                       9
Not Applicable                                        7
Sushant Lok 1 Builder Floors                          6
Experion Windchants3.8 ★                              6
Ansals Palam Vihar                                    6
DLF New Town Heights 24.0 ★                           5
DLF City Phase 1                                      5
Ansal Sushant Lok Plots4.1 ★                          4
nul                                                   4
Ansals Florence Villa                                 4
DLF Alameda                                           4
Unitech Aspen Greens                                  4
Unitech Nirvana Birch Court                           4
Vatika India Next4.1 ★                                4
Luxury DLF City Floors                                3
DLF City Plots Phase 3                                3
Puri Diplomatic Greens4.0 ★                           3
Tata Primanti4.1 ★                                    3
Anant Raj Estates                                     3
Central Park Flower Valley                            3
Bestech Park View Ananda4.2 ★                         3
HUDA Ashok Vihar Phase 13.9 ★                         3
Hans Enclave                                          3
Housing Board Colony                                  3
Malibu Towne                                          3
Sector 14 RWA                                         3
Palam Vihar Extension West Zone RWA                   3
Rattan Garden                                         3
SS Aaron Ville                                        3
Vatika Signature Villas                               3
Eros Rosewood City4.0 ★                               3
Eros Rosewood Villas                                  3
BPTP Astaire Gardens3.7 ★                             3
Silverglades Tarudhan Valley Golf Resort              3
Ansal API Esencia3.7 ★                                2
Suncity Essel Towers4.2 ★                             2
DLF New Town Heights3.7 ★                             2
Ansal Sushant Residency                               2
DLF South City 1                                      2
Emaar Emerald Hills4.1 ★                              2
Unitech Deerwood Chase                                2
DLF City Plots Phase 4                                2
shivpuri                                              2
Spaze Privy3.9 ★                                      2
Project Mianwali Colony                               2
Project Housing Board Colony                          2
IFFCO Nagar and 17B RWA                               2
Bhim Garh Kheri                                       2
Sobha City                                            2
Ardee City3.8 ★                                       2
Signature Global City 92                              2
Unitech Escape3.8 ★                                   2
Satya The Hermitage3.5 ★                              2
Suncity Township4.1 ★                                 2
Emaar The Palm Springs                                2
Nirvana Cedar Crest                                   2
SS Hibiscus                                           2
Saksham Welfare Association                           2
Unitech Palms South City 1                            2
BPTP Pedestal                                         2
RWA Sector 46                                         2
Sector 38 RWA                                         2
Grover Homes Sec 4                                    1
FLOOR WISE DESIGNER KOTHI                             1
sector 37                                             1
All Punjabi Welfare Association                       1
huda sector-56 gurgaon                                1
Sector-17C                                            1
private house                                         1
Anant Raj Manor Villas                                1
patel nager house no 927/5                            1
Ashok Vihar Phase 3 Gurgaon                           1
Farrukhnagar                                          1
Prem Kunj                                             1
secter 16a daultabad faridabad house no 313           1
rajendra park sec 105                                 1
Ansal Heights3.2 ★                                    1
Ninex City                                            1
Signature Global Park4.0 ★                            1
My Home                                               1
Surat nagar phase 2                                   1
DLF Gardencity Enclave                                1
Rajendra Park Gurgaon                                 1
house number B-34                                     1
ATS Tourmaline3.9 ★                                   1
Bhawani enclave                                       1
Om Nagar, Sector-11                                   1
DLF The Arbour                                        1
DLF Garden City Floors                                1
Huda Plots                                            1
Tulip Ivory3.5 ★                                      1
Emaar MGF The Palm Drive4.1 ★                         1
bhim nagar, sector 6                                  1
Anamika Enclave                                       1
Laxman vihar phase 2                                  1
MANOHAR NAGAR                                         1
Vatika Sovereign Next                                 1
Surendra Homes Dayanand Colony                        1
DLF The Grove                                         1
RK Excelo                                             1
Anand Garden, Sector-105                              1
Jacobpura Gurugram                                    1
Hero Homes                                            1
Ganpati Heights Apartment                             1
Smart World Gems                                      1
shree krishna homes                                   1
Tulip Yellow                                          1
HUDA Housing Board Colony4.1 ★                        1
Laxmi Garden Sector-11                                1
Ansal Celebrity Homes                                 1
Shri Shyam Residency                                  1
mian wali                                             1
HUDA Plot Sector 38                                   1
ROW HOUSE                                             1
Madan puri                                            1
Indiabulls Centrum Park3.7 ★                          1
Jacobpura                                             1
Huda Flats                                            1
Krishna Palace                                        1
Naman Residency                                       1
Sai Kripa Floors 5                                    1
DLF City Plot Phase 4                                 1
Bhim Nagar Society                                    1
Shivaji Nagar Residential                             1
Raj Villas                                            1
mahavir pura                                          1
jacob pura                                            1
Nirmal Enclave, Maruti Kunj Road                      1
Ansal Esencia Sovereign Floors                        1
Greenopolis                                           1
Vipul World3.9 ★                                      1
Sare Crescent Parc Royal Greens Phase 1               1
Anshul                                                1
SS Omnia                                              1
Suncity Avenue 76                                     1
Sheetla Enclave                                       1
sneh vihar                                            1
Adani Brahma Samsara4.2 ★                             1
DLF City Plot Phase 3                                 1
Signature Global City 63A                             1
rattan vihar rajendra park                            1
Ashok vihar phase III Extension                       1
Ansal                                                 1
Nitin Vihar                                           1
Sector 15 Part 2 RWA                                  1
u block dlf phase 3 road no 21                        1
cloudnine cottages                                    1
Landmark House                                        1
nirvana country                                       1
Kothi                                                 1
Birla Navya                                           1
Central Park Flower Valley Cerise Floors              1
Ansal API Spanish Court                               1
4S Aradhya Homes                                      1
Ireo Victory Valley4.1 ★                              1
Ansal Florence Super                                  1
Smart World Orchard                                   1
Unitech South City 23.8 ★                             1
DLF Floors Phase 3                                    1
Signature Global City                                 1
Signature Global City 81                              1
Central Park                                          1
Ansal Sushant Lok                                     1
Nirvana Country                                       1
Vatika The Seven Lamps3.8 ★                           1
Unitech Greenwood City3.6 ★                           1
Independent House Sector 45                           1
Ireo Victory Valley4.0 ★                              1
Satya The Legend3.8 ★                                 1
DLF Pink Town House4.0 ★                              1
Arjun Marg/ Sector- 26 Phase- 1/ Golf Course Road     1
Vatika Independent Floors3.8 ★                        1
The Laburnum                                          1
Ansal Sushant Lok 2                                   1
Godrej Meridien                                       1
Sector 57 Huda                                        1
Huda                                                  1
Huda Floor                                            1
Name: count, dtype: int64

In [136]:
df['society'] = df['society'].str.lower()

    now lets remove these digits and characters from the names

In [137]:
df['society'] = df['society'].str.replace(r'[\d\★]', '', regex=True)

In [138]:
df['society'].value_counts()

society
international city by sobha phase                 49
vipul tatvam villa                                27
emaar mgf marbella                                26
dlf city plots phase                              16
unitech uniworld resorts                          14
unitech espace                                    11
dlf city plots                                    11
bptp visionnaire                                   9
uppal southend.                                    9
eldeco mansionz                                    9
not applicable                                     7
sushant lok  builder floors                        6
experion windchants.                               6
ansals palam vihar                                 6
dlf new town heights .                             5
sector  rwa                                        5
dlf city phase                                     5
ansal sushant lok plots.                           4
nul                                                4
ansals florence villa                              4
dlf alameda                                        4
unitech aspen greens                               4
unitech nirvana birch court                        4
vatika india next.                                 4
luxury dlf city floors                             3
puri diplomatic greens.                            3
tata primanti.                                     3
anant raj estates                                  3
central park flower valley                         3
bestech park view ananda.                          3
huda ashok vihar phase .                           3
hans enclave                                       3
housing board colony                               3
malibu towne                                       3
palam vihar extension west zone rwa                3
rattan garden                                      3
signature global city                              3
ss aaron ville                                     3
vatika signature villas                            3
eros rosewood city.                                3
eros rosewood villas                               3
bptp astaire gardens.                              3
silverglades tarudhan valley golf resort           3
ansal api esencia.                                 2
suncity essel towers.                              2
dlf new town heights.                              2
ansal sushant residency                            2
dlf south city                                     2
emaar emerald hills.                               2
unitech deerwood chase                             2
shivpuri                                           2
spaze privy.                                       2
project mianwali colony                            2
project housing board colony                       2
iffco nagar and b rwa                              2
bhim garh kheri                                    2
sobha city                                         2
ardee city.                                        2
dlf city plot phase                                2
unitech escape.                                    2
satya the hermitage.                               2
suncity township.                                  2
nirvana country                                    2
emaar the palm springs                             2
nirvana cedar crest                                2
ireo victory valley.                               2
ss hibiscus                                        2
saksham welfare association                        2
unitech palms south city                           2
bptp pedestal                                      2
rwa sector                                         2
grover homes sec                                   1
floor wise designer kothi                          1
sector                                             1
all punjabi welfare association                    1
huda sector- gurgaon                               1
sector-c                                           1
private house                                      1
anant raj manor villas                             1
patel nager house no /                             1
ashok vihar phase  gurgaon                         1
farrukhnagar                                       1
prem kunj                                          1
secter a daultabad faridabad house no              1
rajendra park sec                                  1
ansal heights.                                     1
ninex city                                         1
signature global park.                             1
my home                                            1
surat nagar phase                                  1
dlf gardencity enclave                             1
rajendra park gurgaon                              1
house number b-                                    1
ats tourmaline.                                    1
bhawani enclave                                    1
om nagar, sector-                                  1
dlf the arbour                                     1
dlf garden city floors                             1
huda plots                                         1
tulip ivory.                                       1
emaar mgf the palm drive.                          1
bhim nagar, sector                                 1
anamika enclave                                    1
laxman vihar phase                                 1
manohar nagar                                      1
vatika sovereign next                              1
surendra homes dayanand colony                     1
dlf the grove                                      1
rk excelo                                          1
anand garden, sector-                              1
jacobpura gurugram                                 1
hero homes                                         1
ganpati heights apartment                          1
smart world gems                                   1
shree krishna homes                                1
tulip yellow                                       1
huda housing board colony.                         1
laxmi garden sector-                               1
ansal celebrity homes                              1
shri shyam residency                               1
mian wali                                          1
huda plot sector                                   1
row house                                          1
madan puri                                         1
indiabulls centrum park.                           1
jacobpura                                          1
huda flats                                         1
krishna palace                                     1
naman residency                                    1
sai kripa floors                                   1
bhim nagar society                                 1
shivaji nagar residential                          1
raj villas                                         1
mahavir pura                                       1
jacob pura                                         1
nirmal enclave, maruti kunj road                   1
ansal esencia sovereign floors                     1
greenopolis                                        1
vipul world.                                       1
sare crescent parc royal greens phase              1
anshul                                             1
ss omnia                                           1
suncity avenue                                     1
sheetla enclave                                    1
sneh vihar                                         1
adani brahma samsara.                              1
signature global city a                            1
rattan vihar rajendra park                         1
ashok vihar phase iii extension                    1
ansal                                              1
nitin vihar                                        1
sector  part  rwa                                  1
u block dlf phase  road no                         1
cloudnine cottages                                 1
landmark house                                     1
kothi                                              1
birla navya                                        1
central park flower valley cerise floors           1
ansal api spanish court                            1
s aradhya homes                                    1
ansal florence super                               1
smart world orchard                                1
unitech south city .                               1
dlf floors phase                                   1
signature global city                              1
central park                                       1
ansal sushant lok                                  1
vatika the seven lamps.                            1
unitech greenwood city.                            1
independent house sector                           1
satya the legend.                                  1
dlf pink town house.                               1
arjun marg/ sector-  phase- / golf course road     1
vatika independent floors.                         1
the laburnum                                       1
ansal sushant lok                                  1
godrej meridien                                    1
sector  huda                                       1
huda                                               1
huda floor                                         1
Name: count, dtype: int64

**price**<br>

In [139]:
df['price'].value_counts()

price
3.5 Crore           19
5.5 Crore           17
6.5 Crore           16
6 Crore             14
5 Crore             13
4.5 Crore           13
70 Lac              13
75 Lac              13
50 Lac              13
8 Crore             13
8.5 Crore           12
7 Crore             12
2.5 Crore           12
85 Lac              12
4 Crore             11
1.5 Crore           11
9 Crore             10
10 Crore            10
2.25 Crore          10
90 Lac              10
45 Lac              10
60 Lac              10
Price on Request    10
12 Crore             9
2 Crore              9
9.5 Crore            9
1.1 Crore            9
80 Lac               9
1.7 Crore            9
3.75 Crore           8
1 Crore              8
1.6 Crore            8
4.6 Crore            8
11 Crore             8
6.75 Crore           8
2.1 Crore            7
12.5 Crore           7
65 Lac               7
55 Lac               7
95 Lac               7
1.3 Crore            7
1.2 Crore            7
1.35 Crore           7
40 Lac               7
5.7 Crore            6
13.5 Crore           6
6.25 Crore           6
5.6 Crore            6
7.25 Crore           6
3.25 Crore           6
7.5 Crore            6
3.6 Crore            6
1.45 Crore           6
2.75 Crore           6
1.15 Crore           6
2.95 Crore           6
16 Crore             6
4.25 Crore           6
10.5 Crore           6
3 Crore              5
15 Crore             5
8.25 Crore           5
4.75 Crore           5
5.75 Crore           5
17 Crore             5
35 Lac               5
2.8 Crore            5
1.25 Crore           5
1.8 Crore            5
38 Lac               5
5.25 Crore           4
8.4 Crore            4
3.3 Crore            4
13 Crore             4
5.8 Crore            4
3.2 Crore            4
11.5 Crore           4
6.8 Crore            4
42 Lac               4
2.4 Crore            4
37 Lac               4
4.7 Crore            4
1.65 Crore           4
1.4 Crore            4
4.35 Crore           4
18 Crore             4
9.25 Crore           4
20 Crore             3
1.95 Crore           3
4.45 Crore           3
7.35 Crore           3
3.4 Crore            3
7.2 Crore            3
2.55 Crore           3
3.55 Crore           3
5.65 Crore           3
1.55 Crore           3
3.85 Crore           3
3.1 Crore            3
6.95 Crore           3
2.2 Crore            3
82 Lac               3
1.16 Crore           3
34 Lac               3
49 Lac               3
62 Lac               3
2.3 Crore            3
32 Lac               3
5.15 Crore           3
92 Lac               3
1.85 Crore           3
4.3 Crore            3
1.9 Crore            3
2.9 Crore            3
19 Crore             3
6.4 Crore            3
10.85 Crore          2
11.95 Crore          2
5.4 Crore            2
7.99 Crore           2
10.45 Crore          2
19.5 Crore           2
67 Lac               2
3.05 Crore           2
6.3 Crore            2
58 Lac               2
11.25 Crore          2
66 Lac               2
48 Lac               2
36 Lac               2
1.75 Crore           2
30 Lac               2
14 Crore             2
1.05 Crore           2
3.35 Crore           2
3.15 Crore           2
89 Lac               2
9.9 Crore            2
2.15 Crore           2
58.25 Lac            2
15.5 Crore           2
10.55 Crore          2
3.65 Crore           2
26 Crore             2
3.51 Crore           2
8.49 Crore           2
4.95 Crore           2
7.1 Crore            2
11.75 Crore          2
10.75 Crore          1
7.6 Crore            1
10.56 Crore          1
5.46 Crore           1
55.11 Lac            1
7.49 Crore           1
12.39 Crore          1
8.8 Crore            1
7.69 Crore           1
8.7 Crore            1
6.2 Crore            1
5.9 Crore            1
5.85 Crore           1
5.35 Crore           1
6.6 Crore            1
61 Lac               1
7.05 Crore           1
3.69 Crore           1
11.3 Crore           1
4.02 Crore           1
3.93 Crore           1
15.5 Lac             1
4.12 Crore           1
1.87 Crore           1
22 Lac               1
3.12 Crore           1
7.5 Lac              1
2.58 Crore           1
8.95 Crore           1
13.2 Crore           1
51 Lac               1
53 Lac               1
63 Lac               1
1.72 Crore           1
78 Lac               1
1.52 Crore           1
52 Lac               1
4.65 Crore           1
6.1 Crore            1
68 Lac               1
1.07 Crore           1
5.2 Crore            1
42.75 Lac            1
47 Lac               1
71 Lac               1
52.5 Lac             1
1.44 Crore           1
3.71 Crore           1
18 Lac               1
3.08 Crore           1
29 Lac               1
24 Lac               1
44 Lac               1
83 Lac               1
98 Lac               1
47.5 Lac             1
3.09 Crore           1
74 Lac               1
69 Lac               1
2.43 Crore           1
13 Lac               1
96 Lac               1
18.02 Crore          1
65.8 Lac             1
1.34 Crore           1
46 Lac               1
2.6 Crore            1
3.87 Crore           1
1.39 Crore           1
59 Lac               1
27 Lac               1
8.1 Crore            1
14.75 Crore          1
9.54 Crore           1
17.3 Crore           1
18.9 Crore           1
24 Crore             1
7.46 Crore           1
59.95 Lac            1
3.99 Crore           1
6.81 Crore           1
8.81 Crore           1
8.9 Crore            1
4.49 Crore           1
22 Crore             1
4.15 Crore           1
7.3 Crore            1
18.5 Crore           1
27.5 Crore           1
8.31 Crore           1
6.21 Crore           1
1.83 Crore           1
5.1 Crore            1
3.9 Crore            1
2.01 Crore           1
5.88 Crore           1
52.75 Lac            1
46.75 Lac            1
12.25 Crore          1
9.4 Crore            1
10.3 Crore           1
8.45 Crore           1
6.15 Crore           1
2.47 Crore           1
3.7 Crore            1
18.4 Crore           1
4.4 Crore            1
99 Lac               1
2.65 Crore           1
1.27 Crore           1
11.29 Crore          1
4.31 Crore           1
11.58 Crore          1
8.48 Crore           1
8.2 Crore            1
5.51 Crore           1
3.49 Crore           1
2.99 Crore           1
9.19 Crore           1
1.64 Crore           1
9.35 Crore           1
4.05 Crore           1
8.75 Crore           1
23 Crore             1
2.45 Crore           1
7.85 Crore           1
25 Crore             1
2.68 Crore           1
2.7 Crore            1
1.04 Crore           1
9.85 Crore           1
1.18 Crore           1
15.1 Crore           1
9.01 Crore           1
9.8 Crore            1
4.99 Crore           1
8.6 Crore            1
9.55 Crore           1
2.35 Crore           1
18.25 Crore          1
5.3 Crore            1
10.8 Crore           1
31.5 Crore           1
4.1 Crore            1
7.65 Crore           1
6.46 Crore           1
6.44 Crore           1
7.8 Crore            1
3.8 Crore            1
7.45 Crore           1
7.42 Crore           1
6.09 Crore           1
2.98 Crore           1
Name: count, dtype: int64

In [140]:
df['price'] = df['price'].str.lower()

    the price column is string dtype here. so i converted every value(except price on value and NAN) to crore and make them float type

In [141]:
def price_to_number(price):
    if pd.isna(price):
        return np.nan
    if 'lac' in price:
        return float(price.replace('lac','').strip())/100
    elif 'crore' in price:
        return float(price.replace('crore','').strip())
    else: return price
    

df['price'] = df['price'].apply(price_to_number)

In [142]:
df.head()

,property_name,sector,society,price,rate,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,sector 70a,bptp visionnaire,5.25,"₹ 20,115/sq.ft.",(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,sector 21a faridabad,NaN,5.7,"₹ 105,751/sq.ft.",(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5 Bedrooms,4 Bathrooms,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,sushant lok phase 1,NaN,2.1,"₹ 38,251/sq.ft.",(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10 Bedrooms,10 Bathrooms,3+ Balconies,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,sector 54,NaN,5.0,"₹ 43,066/sq.ft.",(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21 Bedrooms,21 Bathrooms,3+ Balconies,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,sushant lok phase 1,NaN,3.0,"₹ 53,763/sq.ft.",(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12 Bedrooms,12 Bathrooms,3+ Balconies,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

    the rate column name should be price per sq ft instead of rate.
        1) so we will first make remvoe the sq/ft from the values and then make them numerical dtype
        2) also change the name of the column 'rate' -> 'price_per_sqft'

In [143]:
df.rename(columns={'rate':'price_per_sqft'},inplace=True)

In [144]:
df['price_per_sqft'] = df['price_per_sqft'].str.split('/').str.get(0).str.split(' ').str.get(1).str.replace(',','').astype(float)

In [145]:
df.head()

,property_name,sector,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,sector 70a,bptp visionnaire,5.25,20115.0,(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,sector 21a faridabad,NaN,5.7,105751.0,(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5 Bedrooms,4 Bathrooms,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,sushant lok phase 1,NaN,2.1,38251.0,(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10 Bedrooms,10 Bathrooms,3+ Balconies,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,sector 54,NaN,5.0,43066.0,(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21 Bedrooms,21 Bathrooms,3+ Balconies,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,sushant lok phase 1,NaN,3.0,53763.0,(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12 Bedrooms,12 Bathrooms,3+ Balconies,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [146]:
df['area'] = round((df['price']/df['price_per_sqft'])*10000000,2).astype(float)

**bedroom**<br>
    converting bedroom to numerical dtype by removing the Bedrooms string from the string

In [147]:
df['bedRoom'].value_counts()

bedRoom
4 Bedrooms     240
5 Bedrooms     197
3 Bedrooms     151
2 Bedrooms      91
6 Bedrooms      82
9 Bedrooms      45
1 Bedroom       38
8 Bedrooms      34
7 Bedrooms      32
12 Bedrooms     29
10 Bedrooms     21
16 Bedrooms     12
13 Bedrooms      4
18 Bedrooms      2
19 Bedrooms      2
11 Bedrooms      2
21 Bedrooms      1
20 Bedrooms      1
36 Bedrooms      1
34 Bedrooms      1
14 Bedrooms      1
Name: count, dtype: int64

    here i removed the null values where the price column is null(i have to remove these rows because area values for these prices are also NULL, so i was not able to predict the price values)

In [148]:
df = df[~df['price'].isnull()]

In [149]:
df['bedRoom'] = df['bedRoom'].str.split(' ').str.get(0).str.strip().astype(float)

**bathroom**<br>
    removing the bathroom keyword from the string

In [150]:
df['bathroom'].value_counts()

bathroom
4 Bathrooms     231
3 Bathrooms     166
5 Bathrooms     134
2 Bathrooms     116
6 Bathrooms      86
1 Bathroom       66
9 Bathrooms      41
7 Bathrooms      37
8 Bathrooms      28
12 Bathrooms     22
10 Bathrooms     11
16 Bathrooms      7
13 Bathrooms      4
18 Bathrooms      4
11 Bathrooms      4
20 Bathrooms      3
17 Bathrooms      3
14 Bathrooms      2
21 Bathrooms      1
36 Bathrooms      1
34 Bathrooms      1
Name: count, dtype: int64

In [151]:
df['bathroom'] = df['bathroom'].str.split(' ').str.get(0).str.strip().astype(float)

**balcony**<br>
    we can't convert it into a numerical value because there is a value '3+ Balconies'

In [152]:
df['balcony'].value_counts()

balcony
3+ Balconies    361
2 Balconies     221
3 Balconies     162
No Balcony      117
1 Balcony       107
Name: count, dtype: int64

In [153]:
df['balcony'] = df['balcony'].str.split(' ').str.get(0).str.strip()

    i am not able to get any useful information from the **address* column so i am going to remove it, but if later on if it is required then i will take the action

In [154]:
df.drop(columns=['address'], inplace=True)

**noOfFloor**<br>

In [155]:
df['noOfFloor'].value_counts()

noOfFloor
3 Floors     304
2 Floors     294
1 Floors     181
4 Floors     133
5 Floors       9
0 Floors       6
14 Floors      3
6 Floors       3
12 Floors      2
10 Floors      2
11 Floors      2
02 Floors      1
21 Floors      1
27 Floors      1
13 Floors      1
20 Floors      1
41 Floors      1
51 Floors      1
16 Floors      1
33 Floors      1
Name: count, dtype: int64


    i am creating a copy for my dataframe so that if there is any trouble i can come back to my real dataframe

In [156]:
df1 = df.copy()

    i am changing the name of the 'noOfFloor' to 'floorNum'

In [157]:
df1['noOfFloor'] = df1['noOfFloor'].str.split(' ').str.get(0).str.strip().astype('Int64')

In [158]:
df1.rename(columns={'noOfFloor':'floorNum'},inplace=True)

In [159]:
df1.insert(1, 'property_type', 'house')

In [160]:
df1.to_csv('house_cleaned.csv', index=False)